/*
GitBundle API

Testing StatusCheckAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package gitbundlesdk

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/gitbundle/sdk-go"
)

func Test_gitbundlesdk_StatusCheckAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test StatusCheckAPIService GetChecks", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var repoRef string
		var commitSha string

		resp, httpRes, err := apiClient.StatusCheckAPI.GetChecks(context.Background(), repoRef, commitSha).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StatusCheckAPIService GetRecent", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var repoRef string

		resp, httpRes, err := apiClient.StatusCheckAPI.GetRecent(context.Background(), repoRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StatusCheckAPIService PutCheckReport", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var repoRef string
		var commitSha string

		resp, httpRes, err := apiClient.StatusCheckAPI.PutCheckReport(context.Background(), repoRef, commitSha).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
