/*
GitBundle API

Testing RepositoryAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package gitbundlesdk

import (
	"context"
	openapiclient "github.com/gitbundle/sdk-go"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_gitbundlesdk_RepositoryAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test RepositoryAPIService CommitFiles", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string

		resp, httpRes, err := apiClient.RepositoryAPI.CommitFiles(context.Background(), repoRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService CommitsCalculateDivergence", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string

		resp, httpRes, err := apiClient.RepositoryAPI.CommitsCalculateDivergence(context.Background(), repoRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService DeleteBranch", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string
		var branchName string

		httpRes, err := apiClient.RepositoryAPI.DeleteBranch(context.Background(), repoRef, branchName).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService DeleteRelease", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string
		var tagRef string

		httpRes, err := apiClient.RepositoryAPI.DeleteRelease(context.Background(), repoRef, tagRef).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService DeleteRepositoryRunner", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string
		var runnerUuid string

		httpRes, err := apiClient.RepositoryAPI.DeleteRepositoryRunner(context.Background(), repoRef, runnerUuid).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService DeleteRepositoryVariable", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string
		var variableIdentifier string

		httpRes, err := apiClient.RepositoryAPI.DeleteRepositoryVariable(context.Background(), repoRef, variableIdentifier).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService DeleteTag", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string
		var tagName string

		httpRes, err := apiClient.RepositoryAPI.DeleteTag(context.Background(), repoRef, tagName).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService GeneralUpdate", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string

		resp, httpRes, err := apiClient.RepositoryAPI.GeneralUpdate(context.Background(), repoRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService GetArchive", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string
		var archiveRef string

		resp, httpRes, err := apiClient.RepositoryAPI.GetArchive(context.Background(), repoRef, archiveRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService GetBlame", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string
		var path string

		resp, httpRes, err := apiClient.RepositoryAPI.GetBlame(context.Background(), repoRef, path).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService GetBranch", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string
		var branchName string

		resp, httpRes, err := apiClient.RepositoryAPI.GetBranch(context.Background(), repoRef, branchName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService GetBranches", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string

		resp, httpRes, err := apiClient.RepositoryAPI.GetBranches(context.Background(), repoRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService GetCodeownersValidate", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string

		resp, httpRes, err := apiClient.RepositoryAPI.GetCodeownersValidate(context.Background(), repoRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService GetCommit", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string
		var commitSha string

		resp, httpRes, err := apiClient.RepositoryAPI.GetCommit(context.Background(), repoRef, commitSha).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService GetCommitDiff", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string
		var commitSha string

		resp, httpRes, err := apiClient.RepositoryAPI.GetCommitDiff(context.Background(), repoRef, commitSha).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService GetCommitFileContent", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string
		var commitSha string

		resp, httpRes, err := apiClient.RepositoryAPI.GetCommitFileContent(context.Background(), repoRef, commitSha).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService GetCommits", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string

		resp, httpRes, err := apiClient.RepositoryAPI.GetCommits(context.Background(), repoRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService GetContent", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string
		var path string

		resp, httpRes, err := apiClient.RepositoryAPI.GetContent(context.Background(), repoRef, path).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService GetContributors", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string

		resp, httpRes, err := apiClient.RepositoryAPI.GetContributors(context.Background(), repoRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService GetDiffStats", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string
		var path string

		resp, httpRes, err := apiClient.RepositoryAPI.GetDiffStats(context.Background(), repoRef, path).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService GetDiffs", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string
		var path string

		resp, httpRes, err := apiClient.RepositoryAPI.GetDiffs(context.Background(), repoRef, path).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService GetForks", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string

		resp, httpRes, err := apiClient.RepositoryAPI.GetForks(context.Background(), repoRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService GetGeneral", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string

		resp, httpRes, err := apiClient.RepositoryAPI.GetGeneral(context.Background(), repoRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService GetHasStarred", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string

		resp, httpRes, err := apiClient.RepositoryAPI.GetHasStarred(context.Background(), repoRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService GetImportProgress", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string

		resp, httpRes, err := apiClient.RepositoryAPI.GetImportProgress(context.Background(), repoRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService GetPaths", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string

		resp, httpRes, err := apiClient.RepositoryAPI.GetPaths(context.Background(), repoRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService GetRaw", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string
		var path string

		resp, httpRes, err := apiClient.RepositoryAPI.GetRaw(context.Background(), repoRef, path).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService GetRelease", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string
		var tagRef string

		resp, httpRes, err := apiClient.RepositoryAPI.GetRelease(context.Background(), repoRef, tagRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService GetReleases", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string

		resp, httpRes, err := apiClient.RepositoryAPI.GetReleases(context.Background(), repoRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService GetRepo", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string

		resp, httpRes, err := apiClient.RepositoryAPI.GetRepo(context.Background(), repoRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService GetRepositoryResetedRunnerRegisterToken", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string

		resp, httpRes, err := apiClient.RepositoryAPI.GetRepositoryResetedRunnerRegisterToken(context.Background(), repoRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService GetRepositoryRunner", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string
		var runnerUuid string

		resp, httpRes, err := apiClient.RepositoryAPI.GetRepositoryRunner(context.Background(), repoRef, runnerUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService GetRepositoryRunnerRegisterToken", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string

		resp, httpRes, err := apiClient.RepositoryAPI.GetRepositoryRunnerRegisterToken(context.Background(), repoRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService GetRepositoryRunners", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string

		resp, httpRes, err := apiClient.RepositoryAPI.GetRepositoryRunners(context.Background(), repoRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService GetRepositoryServiceAccounts", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string

		resp, httpRes, err := apiClient.RepositoryAPI.GetRepositoryServiceAccounts(context.Background(), repoRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService GetRepositoryStats", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string

		resp, httpRes, err := apiClient.RepositoryAPI.GetRepositoryStats(context.Background(), repoRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService GetRepositoryVariable", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string
		var variableIdentifier string

		resp, httpRes, err := apiClient.RepositoryAPI.GetRepositoryVariable(context.Background(), repoRef, variableIdentifier).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService GetRepositoryVariables", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string

		resp, httpRes, err := apiClient.RepositoryAPI.GetRepositoryVariables(context.Background(), repoRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService GetSecurity", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string

		resp, httpRes, err := apiClient.RepositoryAPI.GetSecurity(context.Background(), repoRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService GetStars", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string

		resp, httpRes, err := apiClient.RepositoryAPI.GetStars(context.Background(), repoRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService GetTags", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string

		resp, httpRes, err := apiClient.RepositoryAPI.GetTags(context.Background(), repoRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService PatchRepo", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string

		resp, httpRes, err := apiClient.RepositoryAPI.PatchRepo(context.Background(), repoRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService PatchRepositoryRunner", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string
		var runnerUuid string

		resp, httpRes, err := apiClient.RepositoryAPI.PatchRepositoryRunner(context.Background(), repoRef, runnerUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService PatchRepositoryVariable", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string
		var variableIdentifier string

		resp, httpRes, err := apiClient.RepositoryAPI.PatchRepositoryVariable(context.Background(), repoRef, variableIdentifier).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService PatchSecurity", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string

		resp, httpRes, err := apiClient.RepositoryAPI.PatchSecurity(context.Background(), repoRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService PatchStars", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string

		resp, httpRes, err := apiClient.RepositoryAPI.PatchStars(context.Background(), repoRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService PostBranch", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string

		resp, httpRes, err := apiClient.RepositoryAPI.PostBranch(context.Background(), repoRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService PostDefaultBranch", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string

		resp, httpRes, err := apiClient.RepositoryAPI.PostDefaultBranch(context.Background(), repoRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService PostDiffs", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string
		var path2 string

		resp, httpRes, err := apiClient.RepositoryAPI.PostDiffs(context.Background(), repoRef, path2).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService PostMergeCheck", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string
		var path string

		resp, httpRes, err := apiClient.RepositoryAPI.PostMergeCheck(context.Background(), repoRef, path).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService PostPathDetails", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string

		resp, httpRes, err := apiClient.RepositoryAPI.PostPathDetails(context.Background(), repoRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService PostRelease", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string

		resp, httpRes, err := apiClient.RepositoryAPI.PostRelease(context.Background(), repoRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService PostRepo", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.RepositoryAPI.PostRepo(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService PostRepositoryImport", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.RepositoryAPI.PostRepositoryImport(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService PostRepositoryMove", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string

		resp, httpRes, err := apiClient.RepositoryAPI.PostRepositoryMove(context.Background(), repoRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService PostRepositoryPurge", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string

		httpRes, err := apiClient.RepositoryAPI.PostRepositoryPurge(context.Background(), repoRef).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService PostRepositoryVariable", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string

		resp, httpRes, err := apiClient.RepositoryAPI.PostRepositoryVariable(context.Background(), repoRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService PostTag", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string

		resp, httpRes, err := apiClient.RepositoryAPI.PostTag(context.Background(), repoRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService RenameBranch", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string

		resp, httpRes, err := apiClient.RepositoryAPI.RenameBranch(context.Background(), repoRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService RepoRestore", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string

		resp, httpRes, err := apiClient.RepositoryAPI.RepoRestore(context.Background(), repoRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RepositoryAPIService SoftRepositoryDelete", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var repoRef string

		httpRes, err := apiClient.RepositoryAPI.SoftRepositoryDelete(context.Background(), repoRef).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
