/*
 * GitBundle API
 *
 * GitBundle API documentation.
 *
 * The version of the OpenAPI document: 3.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};

/// struct for typed errors of method [`get_checks`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetChecksError {
    Status400(models::JsonErrorResponseNull),
    Status401(models::JsonErrorResponseNull),
    Status403(models::JsonErrorResponseNull),
    Status404(models::JsonErrorResponseNull),
    Status409(models::JsonErrorResponseNull),
    Status429(models::JsonErrorResponseNull),
    Status500(models::JsonErrorResponseNull),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_recent`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetRecentError {
    Status400(models::JsonErrorResponseNull),
    Status401(models::JsonErrorResponseNull),
    Status403(models::JsonErrorResponseNull),
    Status404(models::JsonErrorResponseNull),
    Status409(models::JsonErrorResponseNull),
    Status429(models::JsonErrorResponseNull),
    Status500(models::JsonErrorResponseNull),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`put_check_report`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PutCheckReportError {
    Status400(models::JsonErrorResponseNull),
    Status401(models::JsonErrorResponseNull),
    Status403(models::JsonErrorResponseNull),
    Status404(models::JsonErrorResponseNull),
    Status409(models::JsonErrorResponseNull),
    Status429(models::JsonErrorResponseNull),
    Status500(models::JsonErrorResponseNull),
    UnknownValue(serde_json::Value),
}

pub async fn get_checks(
    configuration: &configuration::Configuration,
    repo_ref: &str,
    commit_sha: &str,
    page: Option<i64>,
    size: Option<i64>,
    query: Option<&str>,
) -> Result<Vec<models::CheckModel>, Error<GetChecksError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_repo_ref = repo_ref;
    let p_commit_sha = commit_sha;
    let p_page = page;
    let p_size = size;
    let p_query = query;

    let uri_str = format!(
        "{}/repos/{repo_ref}/+/checks/commits/{commit_sha}",
        configuration.base_path,
        repo_ref = crate::apis::urlencode(p_repo_ref),
        commit_sha = crate::apis::urlencode(p_commit_sha)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_size {
        req_builder = req_builder.query(&[("size", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query {
        req_builder = req_builder.query(&[("query", &param_value.to_string())]);
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("access_token", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::CheckModel&gt;`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::CheckModel&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetChecksError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn get_recent(
    configuration: &configuration::Configuration,
    repo_ref: &str,
    query: Option<&str>,
    since: Option<i64>,
) -> Result<Vec<String>, Error<GetRecentError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_repo_ref = repo_ref;
    let p_query = query;
    let p_since = since;

    let uri_str = format!(
        "{}/repos/{repo_ref}/+/checks/recent",
        configuration.base_path,
        repo_ref = crate::apis::urlencode(p_repo_ref)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query {
        req_builder = req_builder.query(&[("query", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_since {
        req_builder = req_builder.query(&[("since", &param_value.to_string())]);
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("access_token", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;String&gt;`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;String&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetRecentError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn put_check_report(
    configuration: &configuration::Configuration,
    repo_ref: &str,
    commit_sha: &str,
    check_report_input: models::CheckReportInput,
) -> Result<models::CheckModel, Error<PutCheckReportError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_repo_ref = repo_ref;
    let p_commit_sha = commit_sha;
    let p_check_report_input = check_report_input;

    let uri_str = format!(
        "{}/repos/{repo_ref}/+/checks/commits/{commit_sha}",
        configuration.base_path,
        repo_ref = crate::apis::urlencode(p_repo_ref),
        commit_sha = crate::apis::urlencode(p_commit_sha)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("access_token", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_check_report_input);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CheckModel`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CheckModel`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PutCheckReportError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
