/*
 * GitBundle API
 *
 * GitBundle API documentation.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};

/// struct for typed errors of method [`delete_webhook`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteWebhookError {
    Status400(models::JsonErrorResponseNull),
    Status401(models::JsonErrorResponseNull),
    Status403(models::JsonErrorResponseNull),
    Status404(models::JsonErrorResponseNull),
    Status409(models::JsonErrorResponseNull),
    Status429(models::JsonErrorResponseNull),
    Status500(models::JsonErrorResponseNull),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_execution`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetExecutionError {
    Status400(models::JsonErrorResponseNull),
    Status401(models::JsonErrorResponseNull),
    Status403(models::JsonErrorResponseNull),
    Status404(models::JsonErrorResponseNull),
    Status409(models::JsonErrorResponseNull),
    Status429(models::JsonErrorResponseNull),
    Status500(models::JsonErrorResponseNull),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_executions`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetExecutionsError {
    Status400(models::JsonErrorResponseNull),
    Status401(models::JsonErrorResponseNull),
    Status403(models::JsonErrorResponseNull),
    Status404(models::JsonErrorResponseNull),
    Status409(models::JsonErrorResponseNull),
    Status429(models::JsonErrorResponseNull),
    Status500(models::JsonErrorResponseNull),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_webhook`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetWebhookError {
    Status400(models::JsonErrorResponseNull),
    Status401(models::JsonErrorResponseNull),
    Status403(models::JsonErrorResponseNull),
    Status404(models::JsonErrorResponseNull),
    Status409(models::JsonErrorResponseNull),
    Status429(models::JsonErrorResponseNull),
    Status500(models::JsonErrorResponseNull),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_webhooks`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetWebhooksError {
    Status400(models::JsonErrorResponseNull),
    Status401(models::JsonErrorResponseNull),
    Status403(models::JsonErrorResponseNull),
    Status404(models::JsonErrorResponseNull),
    Status409(models::JsonErrorResponseNull),
    Status429(models::JsonErrorResponseNull),
    Status500(models::JsonErrorResponseNull),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`patch_webhook`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PatchWebhookError {
    Status400(models::JsonErrorResponseNull),
    Status401(models::JsonErrorResponseNull),
    Status403(models::JsonErrorResponseNull),
    Status404(models::JsonErrorResponseNull),
    Status409(models::JsonErrorResponseNull),
    Status429(models::JsonErrorResponseNull),
    Status500(models::JsonErrorResponseNull),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_retrigger`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostRetriggerError {
    Status400(models::JsonErrorResponseNull),
    Status401(models::JsonErrorResponseNull),
    Status403(models::JsonErrorResponseNull),
    Status404(models::JsonErrorResponseNull),
    Status409(models::JsonErrorResponseNull),
    Status429(models::JsonErrorResponseNull),
    Status500(models::JsonErrorResponseNull),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`post_webhook`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostWebhookError {
    Status400(models::JsonErrorResponseNull),
    Status401(models::JsonErrorResponseNull),
    Status403(models::JsonErrorResponseNull),
    Status404(models::JsonErrorResponseNull),
    Status409(models::JsonErrorResponseNull),
    Status429(models::JsonErrorResponseNull),
    Status500(models::JsonErrorResponseNull),
    UnknownValue(serde_json::Value),
}

pub async fn delete_webhook(
    configuration: &configuration::Configuration,
    repo_ref: &str,
    webhook_identifier: &str,
) -> Result<(), Error<DeleteWebhookError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_repo_ref = repo_ref;
    let p_path_webhook_identifier = webhook_identifier;

    let uri_str = format!(
        "{}/repos/{repo_ref}/+/webhooks/{webhook_identifier}",
        configuration.base_path,
        repo_ref = crate::apis::urlencode(p_path_repo_ref),
        webhook_identifier = crate::apis::urlencode(p_path_webhook_identifier)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("access_token", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteWebhookError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn get_execution(
    configuration: &configuration::Configuration,
    repo_ref: &str,
    webhook_identifier: &str,
    webhook_execution_id: i64,
) -> Result<models::WebhookExecutionModel, Error<GetExecutionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_repo_ref = repo_ref;
    let p_path_webhook_identifier = webhook_identifier;
    let p_path_webhook_execution_id = webhook_execution_id;

    let uri_str = format!(
        "{}/repos/{repo_ref}/+/webhooks/{webhook_identifier}/executions/{webhook_execution_id}",
        configuration.base_path,
        repo_ref = crate::apis::urlencode(p_path_repo_ref),
        webhook_identifier = crate::apis::urlencode(p_path_webhook_identifier),
        webhook_execution_id = p_path_webhook_execution_id
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("access_token", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::WebhookExecutionModel`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::WebhookExecutionModel`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetExecutionError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn get_executions(
    configuration: &configuration::Configuration,
    repo_ref: &str,
    webhook_identifier: &str,
) -> Result<Vec<models::WebhookExecutionModel>, Error<GetExecutionsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_repo_ref = repo_ref;
    let p_path_webhook_identifier = webhook_identifier;

    let uri_str = format!(
        "{}/repos/{repo_ref}/+/webhooks/{webhook_identifier}/executions",
        configuration.base_path,
        repo_ref = crate::apis::urlencode(p_path_repo_ref),
        webhook_identifier = crate::apis::urlencode(p_path_webhook_identifier)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("access_token", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::WebhookExecutionModel&gt;`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::WebhookExecutionModel&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetExecutionsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn get_webhook(
    configuration: &configuration::Configuration,
    repo_ref: &str,
    webhook_identifier: &str,
) -> Result<models::WebhookModel, Error<GetWebhookError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_repo_ref = repo_ref;
    let p_path_webhook_identifier = webhook_identifier;

    let uri_str = format!(
        "{}/repos/{repo_ref}/+/webhooks/{webhook_identifier}",
        configuration.base_path,
        repo_ref = crate::apis::urlencode(p_path_repo_ref),
        webhook_identifier = crate::apis::urlencode(p_path_webhook_identifier)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("access_token", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::WebhookModel`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::WebhookModel`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetWebhookError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn get_webhooks(
    configuration: &configuration::Configuration,
    repo_ref: &str,
    page: Option<i64>,
    size: Option<i64>,
    query: Option<&str>,
    sort: Option<models::WebhookSort>,
    order: Option<models::OrderOption>,
) -> Result<Vec<models::WebhookModel>, Error<GetWebhooksError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_repo_ref = repo_ref;
    let p_query_page = page;
    let p_query_size = size;
    let p_query_query = query;
    let p_query_sort = sort;
    let p_query_order = order;

    let uri_str = format!(
        "{}/repos/{repo_ref}/+/webhooks",
        configuration.base_path,
        repo_ref = crate::apis::urlencode(p_path_repo_ref)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_page {
        req_builder = req_builder.query(&[("page", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_size {
        req_builder = req_builder.query(&[("size", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_query {
        req_builder = req_builder.query(&[("query", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_sort {
        req_builder = req_builder.query(&[("sort", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_order {
        req_builder = req_builder.query(&[("order", &param_value.to_string())]);
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("access_token", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::WebhookModel&gt;`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::WebhookModel&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetWebhooksError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn patch_webhook(
    configuration: &configuration::Configuration,
    repo_ref: &str,
    webhook_identifier: &str,
    webhook_patch_input: models::WebhookPatchInput,
) -> Result<models::WebhookModel, Error<PatchWebhookError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_repo_ref = repo_ref;
    let p_path_webhook_identifier = webhook_identifier;
    let p_body_webhook_patch_input = webhook_patch_input;

    let uri_str = format!(
        "{}/repos/{repo_ref}/+/webhooks/{webhook_identifier}",
        configuration.base_path,
        repo_ref = crate::apis::urlencode(p_path_repo_ref),
        webhook_identifier = crate::apis::urlencode(p_path_webhook_identifier)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("access_token", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_webhook_patch_input);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::WebhookModel`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::WebhookModel`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PatchWebhookError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn post_retrigger(
    configuration: &configuration::Configuration,
    repo_ref: &str,
    webhook_identifier: &str,
    webhook_execution_id: i64,
) -> Result<models::WebhookExecutionModel, Error<PostRetriggerError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_repo_ref = repo_ref;
    let p_path_webhook_identifier = webhook_identifier;
    let p_path_webhook_execution_id = webhook_execution_id;

    let uri_str = format!("{}/repos/{repo_ref}/+/webhooks/{webhook_identifier}/executions/{webhook_execution_id}/retrigger", configuration.base_path, repo_ref=crate::apis::urlencode(p_path_repo_ref), webhook_identifier=crate::apis::urlencode(p_path_webhook_identifier), webhook_execution_id=p_path_webhook_execution_id);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("access_token", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::WebhookExecutionModel`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::WebhookExecutionModel`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PostRetriggerError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn post_webhook(
    configuration: &configuration::Configuration,
    repo_ref: &str,
    webhook_create_input: models::WebhookCreateInput,
) -> Result<models::WebhookModel, Error<PostWebhookError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_repo_ref = repo_ref;
    let p_body_webhook_create_input = webhook_create_input;

    let uri_str = format!(
        "{}/repos/{repo_ref}/+/webhooks",
        configuration.base_path,
        repo_ref = crate::apis::urlencode(p_path_repo_ref)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.query(&[("access_token", value)]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref auth_conf) = configuration.basic_auth {
        req_builder = req_builder.basic_auth(auth_conf.0.to_owned(), auth_conf.1.to_owned());
    };
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_webhook_create_input);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::WebhookModel`"))),
            ContentType::Unsupported(unknown_type) => Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::WebhookModel`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<PostWebhookError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
