/*
 * GitBundle API
 *
 * GitBundle API documentation.
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdminPatchInput {
    #[serde(rename = "admin")]
    pub admin: bool,
}

impl AdminPatchInput {
    pub fn new(admin: bool) -> AdminPatchInput {
        AdminPatchInput { admin }
    }
}
