/*
 * GitBundle API
 *
 * GitBundle API documentation.
 *
 * The version of the OpenAPI document: 3.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CheckPayload {
    #[serde(rename = "data", deserialize_with = "Option::deserialize")]
    pub data: Option<serde_json::Value>,
    #[serde(rename = "kind")]
    pub kind: models::CheckPayloadKind,
    #[serde(rename = "version")]
    pub version: String,
}

impl CheckPayload {
    pub fn new(
        data: Option<serde_json::Value>,
        kind: models::CheckPayloadKind,
        version: String,
    ) -> CheckPayload {
        CheckPayload {
            data,
            kind,
            version,
        }
    }
}
