// GitBundle API
//
// GitBundle API documentation.
//
// The version of the OpenAPI document: 3.0.0
//
// Generated by: https://openapi-generator.tech

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum CommitFileActionType {
    #[serde(rename = "create")]
    #[default]
    Create,
    #[serde(rename = "update")]
    Update,
    #[serde(rename = "delete")]
    Delete,
    #[serde(rename = "move")]
    Move,
    #[serde(rename = "patch_text")]
    PatchText,
}

impl std::fmt::Display for CommitFileActionType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Create => write!(f, "create"),
            Self::Update => write!(f, "update"),
            Self::Delete => write!(f, "delete"),
            Self::Move => write!(f, "move"),
            Self::PatchText => write!(f, "patch_text"),
        }
    }
}
