/*
 * GitBundle API
 *
 * GitBundle API documentation.
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DefApprovals {
    #[serde(
        rename = "require_code_owners",
        skip_serializing_if = "Option::is_none"
    )]
    pub require_code_owners: Option<bool>,
    #[serde(
        rename = "require_latest_commit",
        skip_serializing_if = "Option::is_none"
    )]
    pub require_latest_commit: Option<bool>,
    #[serde(
        rename = "require_minimum_count",
        skip_serializing_if = "Option::is_none"
    )]
    pub require_minimum_count: Option<i64>,
    #[serde(
        rename = "require_no_change_request",
        skip_serializing_if = "Option::is_none"
    )]
    pub require_no_change_request: Option<bool>,
}

impl DefApprovals {
    pub fn new() -> DefApprovals {
        DefApprovals {
            require_code_owners: None,
            require_latest_commit: None,
            require_minimum_count: None,
            require_no_change_request: None,
        }
    }
}
