// GitBundle API
//
// GitBundle API documentation.
//
// The version of the OpenAPI document: 3.0.0
//
// Generated by: https://openapi-generator.tech

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DiffFileContent {
    #[serde(
        rename = "header",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub header: Option<Option<String>>,
    #[serde(
        rename = "hunk",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub hunk: Option<Option<Box<models::HunkHeader>>>,
    #[serde(rename = "lines")]
    pub lines: Vec<String>,
}

impl DiffFileContent {
    pub fn new(lines: Vec<String>) -> DiffFileContent {
        DiffFileContent {
            header: None,
            hunk: None,
            lines,
        }
    }
}
