/*
 * GitBundle API
 *
 * GitBundle API documentation.
 *
 * The version of the OpenAPI document: 3.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GroupMemberUpdateInput {
    #[serde(rename = "role")]
    pub role: models::MembershipRole,
}

impl GroupMemberUpdateInput {
    pub fn new(role: models::MembershipRole) -> GroupMemberUpdateInput {
        GroupMemberUpdateInput { role }
    }
}
