/*
 * GitBundle API
 *
 * GitBundle API documentation.
 *
 * The version of the OpenAPI document: 3.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GroupImportInput {
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "identifier")]
    pub identifier: String,
    #[serde(rename = "is_public")]
    pub is_public: bool,
    #[serde(rename = "parent_ref")]
    pub parent_ref: String,
    #[serde(rename = "provider")]
    pub provider: Box<models::RepoProvider>,
    #[serde(rename = "provider_group")]
    pub provider_group: String,
}

impl GroupImportInput {
    pub fn new(
        identifier: String,
        is_public: bool,
        parent_ref: String,
        provider: models::RepoProvider,
        provider_group: String,
    ) -> GroupImportInput {
        GroupImportInput {
            description: None,
            identifier,
            is_public,
            parent_ref,
            provider: Box::new(provider),
            provider_group,
        }
    }
}
