// GitBundle API
//
// GitBundle API documentation.
//
// The version of the OpenAPI document: 3.0.0
//
// Generated by: https://openapi-generator.tech

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Heatmap {
    #[serde(rename = "contributions")]
    pub contributions: Vec<models::NumContributonWithDate>,
    #[serde(rename = "years")]
    pub years: Vec<i32>,
}

impl Heatmap {
    pub fn new(contributions: Vec<models::NumContributonWithDate>, years: Vec<i32>) -> Heatmap {
        Heatmap {
            contributions,
            years,
        }
    }
}
