/*
 * GitBundle API
 *
 * GitBundle API documentation.
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoginOutput {
    #[serde(rename = "access_token")]
    pub access_token: String,
    #[serde(
        rename = "expires_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub expires_at: Option<Option<i64>>,
    #[serde(
        rename = "two_factor_enabled",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub two_factor_enabled: Option<Option<bool>>,
}

impl LoginOutput {
    pub fn new(access_token: String) -> LoginOutput {
        LoginOutput {
            access_token,
            expires_at: None,
            two_factor_enabled: None,
        }
    }
}
