/*
 * GitBundle API
 *
 * GitBundle API documentation.
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum MembershipSort {
    #[serde(rename = "noop")]
    #[default]
    Noop,
    #[serde(rename = "id")]
    Id,
    #[serde(rename = "created")]
    Created,
}

impl std::fmt::Display for MembershipSort {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Noop => write!(f, "noop"),
            Self::Id => write!(f, "id"),
            Self::Created => write!(f, "created"),
        }
    }
}
