/*
 * GitBundle API
 *
 * GitBundle API documentation.
 *
 * The version of the OpenAPI document: 3.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MembershipUserGroup {
    #[serde(
        rename = "group",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub group: Option<Option<Box<models::GroupModel>>>,
    #[serde(rename = "model")]
    pub model: Box<models::MembershipModel>,
    #[serde(
        rename = "user",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub user: Option<Option<Box<models::UserModel>>>,
}

impl MembershipUserGroup {
    pub fn new(model: models::MembershipModel) -> MembershipUserGroup {
        MembershipUserGroup {
            group: None,
            model: Box::new(model),
            user: None,
        }
    }
}
