/*
 * GitBundle API
 *
 * GitBundle API documentation.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PullreqMergeCheckStatus {
    #[serde(rename = "unchecked")]
    Unchecked,
    #[serde(rename = "conflict")]
    Conflict,
    #[serde(rename = "mergeable")]
    Mergeable,

}

impl std::fmt::Display for PullreqMergeCheckStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Unchecked => write!(f, "unchecked"),
            Self::Conflict => write!(f, "conflict"),
            Self::Mergeable => write!(f, "mergeable"),
        }
    }
}

impl Default for PullreqMergeCheckStatus {
    fn default() -> PullreqMergeCheckStatus {
        Self::Unchecked
    }
}

