// GitBundle API
//
// GitBundle API documentation.
//
// The version of the OpenAPI document: 3.0.0
//
// Generated by: https://openapi-generator.tech

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PullreqReviewerModel {
    #[serde(rename = "created")]
    pub created: i64,
    #[serde(rename = "created_by")]
    pub created_by: i64,
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(
        rename = "latest_review_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub latest_review_id: Option<Option<i64>>,
    #[serde(rename = "pullreq_id")]
    pub pullreq_id: i64,
    #[serde(rename = "repo_id")]
    pub repo_id: i64,
    #[serde(rename = "review_decision")]
    pub review_decision: models::PullreqReviewDecision,
    #[serde(rename = "sha")]
    pub sha: String,
    #[serde(rename = "type")]
    pub r#type: models::PullreqReviewerType,
    #[serde(rename = "updated")]
    pub updated: i64,
    #[serde(rename = "user_id")]
    pub user_id: i64,
}

impl PullreqReviewerModel {
    pub fn new(
        created: i64,
        created_by: i64,
        id: i64,
        pullreq_id: i64,
        repo_id: i64,
        review_decision: models::PullreqReviewDecision,
        sha: String,
        r#type: models::PullreqReviewerType,
        updated: i64,
        user_id: i64,
    ) -> PullreqReviewerModel {
        PullreqReviewerModel {
            created,
            created_by,
            id,
            latest_review_id: None,
            pullreq_id,
            repo_id,
            review_decision,
            sha,
            r#type,
            updated,
            user_id,
        }
    }
}
