/*
 * GitBundle API
 *
 * GitBundle API documentation.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PullreqReviewSubmitInput {
    #[serde(rename = "commit_sha")]
    pub commit_sha: String,
    #[serde(rename = "decision")]
    pub decision: models::PullreqReviewDecision,
}

impl PullreqReviewSubmitInput {
    pub fn new(commit_sha: String, decision: models::PullreqReviewDecision) -> PullreqReviewSubmitInput {
        PullreqReviewSubmitInput {
            commit_sha,
            decision,
        }
    }
}

