// GitBundle API
//
// GitBundle API documentation.
//
// The version of the OpenAPI document: 3.0.0
//
// Generated by: https://openapi-generator.tech

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PullreqReviewerAddInput {
    #[serde(rename = "reviewer_id")]
    pub reviewer_id: i64,
}

impl PullreqReviewerAddInput {
    pub fn new(reviewer_id: i64) -> PullreqReviewerAddInput {
        PullreqReviewerAddInput { reviewer_id }
    }
}
