/*
 * GitBundle API
 *
 * GitBundle API documentation.
 *
 * The version of the OpenAPI document: 3.4.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum RepoFileContentEncodingType {
    #[serde(rename = "utf8")]
    #[default]
    Utf8,
    #[serde(rename = "base64")]
    Base64,
}

impl std::fmt::Display for RepoFileContentEncodingType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Utf8 => write!(f, "utf8"),
            Self::Base64 => write!(f, "base64"),
        }
    }
}
