/*
 * GitBundle API
 *
 * GitBundle API documentation.
 *
 * The version of the OpenAPI document: 3.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RepoUpdateDefaultBranchInput {
    #[serde(rename = "name")]
    pub name: String,
}

impl RepoUpdateDefaultBranchInput {
    pub fn new(name: String) -> RepoUpdateDefaultBranchInput {
        RepoUpdateDefaultBranchInput { name }
    }
}
