// GitBundle API
//
// GitBundle API documentation.
//
// The version of the OpenAPI document: 3.0.0
//
// Generated by: https://openapi-generator.tech

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RuleViolation {
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "params")]
    pub params: Vec<serde_json::Value>,
}

impl RuleViolation {
    pub fn new(code: String, message: String, params: Vec<serde_json::Value>) -> RuleViolation {
        RuleViolation {
            code,
            message,
            params,
        }
    }
}
