/*
 * GitBundle API
 *
 * GitBundle API documentation.
 *
 * The version of the OpenAPI document: 3.4.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RunnerPostInput {
    #[serde(rename = "labels")]
    pub labels: Vec<String>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "release")]
    pub release: String,
    #[serde(rename = "token")]
    pub token: String,
    #[serde(rename = "uuid")]
    pub uuid: String,
}

impl RunnerPostInput {
    pub fn new(
        labels: Vec<String>,
        name: String,
        release: String,
        token: String,
        uuid: String,
    ) -> RunnerPostInput {
        RunnerPostInput {
            labels,
            name,
            release,
            token,
            uuid,
        }
    }
}
