/*
 * GitBundle API
 *
 * GitBundle API documentation.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SseType {
    #[serde(rename = "noop")]
    Noop,
    #[serde(rename = "execution_updated")]
    ExecutionUpdated,
    #[serde(rename = "execution_running")]
    ExecutionRunning,
    #[serde(rename = "execution_completed")]
    ExecutionCompleted,
    #[serde(rename = "execution_canceled")]
    ExecutionCanceled,
    #[serde(rename = "repository_import_completed")]
    RepositoryImportCompleted,
    #[serde(rename = "repository_export_completed")]
    RepositoryExportCompleted,
    #[serde(rename = "pullreq_updated")]
    PullreqUpdated,

}

impl std::fmt::Display for SseType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Noop => write!(f, "noop"),
            Self::ExecutionUpdated => write!(f, "execution_updated"),
            Self::ExecutionRunning => write!(f, "execution_running"),
            Self::ExecutionCompleted => write!(f, "execution_completed"),
            Self::ExecutionCanceled => write!(f, "execution_canceled"),
            Self::RepositoryImportCompleted => write!(f, "repository_import_completed"),
            Self::RepositoryExportCompleted => write!(f, "repository_export_completed"),
            Self::PullreqUpdated => write!(f, "pullreq_updated"),
        }
    }
}

impl Default for SseType {
    fn default() -> SseType {
        Self::Noop
    }
}

