/*
 * GitBundle API
 *
 * GitBundle API documentation.
 *
 * The version of the OpenAPI document: 3.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StageMetadata {
    #[serde(rename = "context")]
    pub context: Box<models::StageContext>,
    #[serde(rename = "stage")]
    pub stage: Box<models::StageModel>,
}

impl StageMetadata {
    pub fn new(context: models::StageContext, stage: models::StageModel) -> StageMetadata {
        StageMetadata {
            context: Box::new(context),
            stage: Box::new(stage),
        }
    }
}
