/*
 * GitBundle API
 *
 * GitBundle API documentation.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TriggerAction {
    #[serde(rename = "noop")]
    Noop,
    #[serde(rename = "branch_created")]
    BranchCreated,
    #[serde(rename = "branch_updated")]
    BranchUpdated,
    #[serde(rename = "tag_created")]
    TagCreated,
    #[serde(rename = "tag_updated")]
    TagUpdated,
    #[serde(rename = "pullreq_created")]
    PullreqCreated,
    #[serde(rename = "pullreq_reopened")]
    PullreqReopened,
    #[serde(rename = "pullreq_branch_updated")]
    PullreqBranchUpdated,
    #[serde(rename = "pullreq_closed")]
    PullreqClosed,
    #[serde(rename = "pullreq_merged")]
    PullreqMerged,

}

impl std::fmt::Display for TriggerAction {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Noop => write!(f, "noop"),
            Self::BranchCreated => write!(f, "branch_created"),
            Self::BranchUpdated => write!(f, "branch_updated"),
            Self::TagCreated => write!(f, "tag_created"),
            Self::TagUpdated => write!(f, "tag_updated"),
            Self::PullreqCreated => write!(f, "pullreq_created"),
            Self::PullreqReopened => write!(f, "pullreq_reopened"),
            Self::PullreqBranchUpdated => write!(f, "pullreq_branch_updated"),
            Self::PullreqClosed => write!(f, "pullreq_closed"),
            Self::PullreqMerged => write!(f, "pullreq_merged"),
        }
    }
}

impl Default for TriggerAction {
    fn default() -> TriggerAction {
        Self::Noop
    }
}

