/*
 * GitBundle API
 *
 * GitBundle API documentation.
 *
 * The version of the OpenAPI document: 3.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TwoFactorGetOutput {
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "qr_uri")]
    pub qr_uri: String,
    #[serde(rename = "secret")]
    pub secret: String,
}

impl TwoFactorGetOutput {
    pub fn new(enabled: bool, qr_uri: String, secret: String) -> TwoFactorGetOutput {
        TwoFactorGetOutput {
            enabled,
            qr_uri,
            secret,
        }
    }
}
