/*
 * GitBundle API
 *
 * GitBundle API documentation.
 *
 * The version of the OpenAPI document: 3.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum VariableSort {
    #[serde(rename = "noop")]
    #[default]
    Noop,
    #[serde(rename = "id")]
    Id,
    #[serde(rename = "name")]
    Name,
    #[serde(rename = "type")]
    Type,
    #[serde(rename = "created")]
    Created,
    #[serde(rename = "updated")]
    Updated,
}

impl std::fmt::Display for VariableSort {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Noop => write!(f, "noop"),
            Self::Id => write!(f, "id"),
            Self::Name => write!(f, "name"),
            Self::Type => write!(f, "type"),
            Self::Created => write!(f, "created"),
            Self::Updated => write!(f, "updated"),
        }
    }
}
