/*
 * GitBundle API
 *
 * GitBundle API documentation.
 *
 * The version of the OpenAPI document: 3.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum WebhookParentType {
    #[serde(rename = "repository")]
    #[default]
    Repository,
    #[serde(rename = "group")]
    Group,
}

impl std::fmt::Display for WebhookParentType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Repository => write!(f, "repository"),
            Self::Group => write!(f, "group"),
        }
    }
}
