/*
 * GitBundle API
 *
 * GitBundle API documentation.
 *
 * The version of the OpenAPI document: 3.3.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkflowModel {
    #[serde(rename = "action")]
    pub action: String,
    #[serde(rename = "action_id")]
    pub action_id: i64,
    #[serde(
        rename = "after_sha",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub after_sha: Option<Option<String>>,
    #[serde(rename = "author_email")]
    pub author_email: String,
    #[serde(
        rename = "author_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub author_id: Option<Option<i64>>,
    #[serde(rename = "author_name")]
    pub author_name: String,
    #[serde(rename = "before_sha")]
    pub before_sha: String,
    #[serde(rename = "context", deserialize_with = "Option::deserialize")]
    pub context: Option<serde_json::Value>,
    #[serde(rename = "created")]
    pub created: i64,
    #[serde(rename = "created_by")]
    pub created_by: i64,
    #[serde(rename = "cron")]
    pub cron: String,
    #[serde(rename = "debug")]
    pub debug: bool,
    #[serde(rename = "deploy")]
    pub deploy: String,
    #[serde(rename = "deploy_id")]
    pub deploy_id: i64,
    #[serde(rename = "error")]
    pub error: String,
    #[serde(rename = "event")]
    pub event: models::TriggerEvent,
    #[serde(rename = "finished")]
    pub finished: i64,
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(
        rename = "inputs",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub inputs: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
    #[serde(rename = "link")]
    pub link: String,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "number")]
    pub number: i64,
    #[serde(rename = "params")]
    pub params: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "repo_id")]
    pub repo_id: i64,
    #[serde(
        rename = "source_repo_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub source_repo_id: Option<Option<i64>>,
    #[serde(
        rename = "source_rev",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub source_rev: Option<Option<String>>,
    #[serde(rename = "started")]
    pub started: i64,
    #[serde(rename = "status")]
    pub status: models::CiStatus,
    #[serde(rename = "target_rev")]
    pub target_rev: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "updated")]
    pub updated: i64,
    #[serde(rename = "version")]
    pub version: i64,
    #[serde(rename = "yaml_provider")]
    pub yaml_provider: models::WorkflowProvider,
    #[serde(rename = "yaml_resolved")]
    pub yaml_resolved: String,
}

impl WorkflowModel {
    pub fn new(
        action: String,
        action_id: i64,
        author_email: String,
        author_name: String,
        before_sha: String,
        context: Option<serde_json::Value>,
        created: i64,
        created_by: i64,
        cron: String,
        debug: bool,
        deploy: String,
        deploy_id: i64,
        error: String,
        event: models::TriggerEvent,
        finished: i64,
        id: i64,
        link: String,
        message: String,
        name: String,
        number: i64,
        params: std::collections::HashMap<String, serde_json::Value>,
        repo_id: i64,
        started: i64,
        status: models::CiStatus,
        target_rev: String,
        title: String,
        updated: i64,
        version: i64,
        yaml_provider: models::WorkflowProvider,
        yaml_resolved: String,
    ) -> WorkflowModel {
        WorkflowModel {
            action,
            action_id,
            after_sha: None,
            author_email,
            author_id: None,
            author_name,
            before_sha,
            context,
            created,
            created_by,
            cron,
            debug,
            deploy,
            deploy_id,
            error,
            event,
            finished,
            id,
            inputs: None,
            link,
            message,
            name,
            number,
            params,
            repo_id,
            source_repo_id: None,
            source_rev: None,
            started,
            status,
            target_rev,
            title,
            updated,
            version,
            yaml_provider,
            yaml_resolved,
        }
    }
}
