/*
 * GitBundle API
 *
 * GitBundle API documentation.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum YamlProvider {
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "git_hub")]
    GitHub,
    #[serde(rename = "git_lab")]
    GitLab,

}

impl std::fmt::Display for YamlProvider {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Unknown => write!(f, "unknown"),
            Self::GitHub => write!(f, "git_hub"),
            Self::GitLab => write!(f, "git_lab"),
        }
    }
}

impl Default for YamlProvider {
    fn default() -> YamlProvider {
        Self::Unknown
    }
}

