generatorName: rust
inputSpec: openapi.json

packageName: gitbundle-sdk
packageVersion: 3.5.0
gitUserId: gitbundle
gitRepoId: sdk

library: reqwest
mockall: true

additionalProperties:
  repositoryUrl: https://github.com/gitbundle/sdk
  authors: "RenovZ <cgsixv@gmail.com>"

# templateDir: template
# files:
#   api.mustache:
#     templateType: API
#   api_client_default.mustache:
#     templateType: API
#     destinationFilename: default.rs
