/*
GitBundle API

GitBundle API documentation.

API version: 3.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbundlesdk

import (
	"encoding/json"
)

// checks if the WorkflowDispatchInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowDispatchInput{}

// WorkflowDispatchInput GitHub Workflow Dispatch Input definition
type WorkflowDispatchInput struct {
	Default interface{} `json:"default,omitempty"`
	// A string shown to users using the deprecated input
	DeprecationMessage NullableString `json:"deprecationMessage,omitempty"`
	// A string description of the input parameter
	Description *string `json:"description,omitempty"`
	// Options of dropdown, required if type = choice
	Options []string `json:"options,omitempty"`
	// A boolean to indicate whether the action requires the input parameter. Set to true when the parameter is required.
	Required NullableBool `json:"required,omitempty"`
	// A string representing the type of the input.
	Type NullableWorkflowDispatchInputType `json:"type,omitempty"`
}

// NewWorkflowDispatchInput instantiates a new WorkflowDispatchInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowDispatchInput() *WorkflowDispatchInput {
	this := WorkflowDispatchInput{}
	return &this
}

// NewWorkflowDispatchInputWithDefaults instantiates a new WorkflowDispatchInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowDispatchInputWithDefaults() *WorkflowDispatchInput {
	this := WorkflowDispatchInput{}
	return &this
}

// GetDefault returns the Default field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkflowDispatchInput) GetDefault() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Default
}

// GetDefaultOk returns a tuple with the Default field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkflowDispatchInput) GetDefaultOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Default) {
		return nil, false
	}
	return &o.Default, true
}

// HasDefault returns a boolean if a field has been set.
func (o *WorkflowDispatchInput) HasDefault() bool {
	if o != nil && !IsNil(o.Default) {
		return true
	}

	return false
}

// SetDefault gets a reference to the given interface{} and assigns it to the Default field.
func (o *WorkflowDispatchInput) SetDefault(v interface{}) {
	o.Default = v
}

// GetDeprecationMessage returns the DeprecationMessage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkflowDispatchInput) GetDeprecationMessage() string {
	if o == nil || IsNil(o.DeprecationMessage.Get()) {
		var ret string
		return ret
	}
	return *o.DeprecationMessage.Get()
}

// GetDeprecationMessageOk returns a tuple with the DeprecationMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkflowDispatchInput) GetDeprecationMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeprecationMessage.Get(), o.DeprecationMessage.IsSet()
}

// HasDeprecationMessage returns a boolean if a field has been set.
func (o *WorkflowDispatchInput) HasDeprecationMessage() bool {
	if o != nil && o.DeprecationMessage.IsSet() {
		return true
	}

	return false
}

// SetDeprecationMessage gets a reference to the given NullableString and assigns it to the DeprecationMessage field.
func (o *WorkflowDispatchInput) SetDeprecationMessage(v string) {
	o.DeprecationMessage.Set(&v)
}

// SetDeprecationMessageNil sets the value for DeprecationMessage to be an explicit nil
func (o *WorkflowDispatchInput) SetDeprecationMessageNil() {
	o.DeprecationMessage.Set(nil)
}

// UnsetDeprecationMessage ensures that no value is present for DeprecationMessage, not even an explicit nil
func (o *WorkflowDispatchInput) UnsetDeprecationMessage() {
	o.DeprecationMessage.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *WorkflowDispatchInput) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowDispatchInput) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *WorkflowDispatchInput) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *WorkflowDispatchInput) SetDescription(v string) {
	o.Description = &v
}

// GetOptions returns the Options field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkflowDispatchInput) GetOptions() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkflowDispatchInput) GetOptionsOk() ([]string, bool) {
	if o == nil || IsNil(o.Options) {
		return nil, false
	}
	return o.Options, true
}

// HasOptions returns a boolean if a field has been set.
func (o *WorkflowDispatchInput) HasOptions() bool {
	if o != nil && !IsNil(o.Options) {
		return true
	}

	return false
}

// SetOptions gets a reference to the given []string and assigns it to the Options field.
func (o *WorkflowDispatchInput) SetOptions(v []string) {
	o.Options = v
}

// GetRequired returns the Required field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkflowDispatchInput) GetRequired() bool {
	if o == nil || IsNil(o.Required.Get()) {
		var ret bool
		return ret
	}
	return *o.Required.Get()
}

// GetRequiredOk returns a tuple with the Required field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkflowDispatchInput) GetRequiredOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Required.Get(), o.Required.IsSet()
}

// HasRequired returns a boolean if a field has been set.
func (o *WorkflowDispatchInput) HasRequired() bool {
	if o != nil && o.Required.IsSet() {
		return true
	}

	return false
}

// SetRequired gets a reference to the given NullableBool and assigns it to the Required field.
func (o *WorkflowDispatchInput) SetRequired(v bool) {
	o.Required.Set(&v)
}

// SetRequiredNil sets the value for Required to be an explicit nil
func (o *WorkflowDispatchInput) SetRequiredNil() {
	o.Required.Set(nil)
}

// UnsetRequired ensures that no value is present for Required, not even an explicit nil
func (o *WorkflowDispatchInput) UnsetRequired() {
	o.Required.Unset()
}

// GetType returns the Type field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkflowDispatchInput) GetType() WorkflowDispatchInputType {
	if o == nil || IsNil(o.Type.Get()) {
		var ret WorkflowDispatchInputType
		return ret
	}
	return *o.Type.Get()
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkflowDispatchInput) GetTypeOk() (*WorkflowDispatchInputType, bool) {
	if o == nil {
		return nil, false
	}
	return o.Type.Get(), o.Type.IsSet()
}

// HasType returns a boolean if a field has been set.
func (o *WorkflowDispatchInput) HasType() bool {
	if o != nil && o.Type.IsSet() {
		return true
	}

	return false
}

// SetType gets a reference to the given NullableWorkflowDispatchInputType and assigns it to the Type field.
func (o *WorkflowDispatchInput) SetType(v WorkflowDispatchInputType) {
	o.Type.Set(&v)
}

// SetTypeNil sets the value for Type to be an explicit nil
func (o *WorkflowDispatchInput) SetTypeNil() {
	o.Type.Set(nil)
}

// UnsetType ensures that no value is present for Type, not even an explicit nil
func (o *WorkflowDispatchInput) UnsetType() {
	o.Type.Unset()
}

func (o WorkflowDispatchInput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowDispatchInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Default != nil {
		toSerialize["default"] = o.Default
	}
	if o.DeprecationMessage.IsSet() {
		toSerialize["deprecationMessage"] = o.DeprecationMessage.Get()
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if o.Options != nil {
		toSerialize["options"] = o.Options
	}
	if o.Required.IsSet() {
		toSerialize["required"] = o.Required.Get()
	}
	if o.Type.IsSet() {
		toSerialize["type"] = o.Type.Get()
	}
	return toSerialize, nil
}

type NullableWorkflowDispatchInput struct {
	value *WorkflowDispatchInput
	isSet bool
}

func (v NullableWorkflowDispatchInput) Get() *WorkflowDispatchInput {
	return v.value
}

func (v *NullableWorkflowDispatchInput) Set(val *WorkflowDispatchInput) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowDispatchInput) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowDispatchInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowDispatchInput(val *WorkflowDispatchInput) *NullableWorkflowDispatchInput {
	return &NullableWorkflowDispatchInput{value: val, isSet: true}
}

func (v NullableWorkflowDispatchInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowDispatchInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
