/*
GitBundle API

GitBundle API documentation.

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbundlesdk

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ActionModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ActionModel{}

// ActionModel struct for ActionModel
type ActionModel struct {
	Created      int64                `json:"created"`
	CreatedBy    int64                `json:"created_by"`
	Description  string               `json:"description"`
	Disabled     bool                 `json:"disabled"`
	Event        NullableTriggerEvent `json:"event,omitempty"`
	Id           int64                `json:"id"`
	Name         string               `json:"name"`
	RepoId       int64                `json:"repo_id"`
	Seq          int64                `json:"seq"`
	Updated      int64                `json:"updated"`
	Version      int64                `json:"version"`
	YamlPath     string               `json:"yaml_path"`
	YamlProvider WorkflowProvider     `json:"yaml_provider"`
}

type _ActionModel ActionModel

// NewActionModel instantiates a new ActionModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActionModel(created int64, createdBy int64, description string, disabled bool, id int64, name string, repoId int64, seq int64, updated int64, version int64, yamlPath string, yamlProvider WorkflowProvider) *ActionModel {
	this := ActionModel{}
	this.Created = created
	this.CreatedBy = createdBy
	this.Description = description
	this.Disabled = disabled
	this.Id = id
	this.Name = name
	this.RepoId = repoId
	this.Seq = seq
	this.Updated = updated
	this.Version = version
	this.YamlPath = yamlPath
	this.YamlProvider = yamlProvider
	return &this
}

// NewActionModelWithDefaults instantiates a new ActionModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActionModelWithDefaults() *ActionModel {
	this := ActionModel{}
	return &this
}

// GetCreated returns the Created field value
func (o *ActionModel) GetCreated() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *ActionModel) GetCreatedOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *ActionModel) SetCreated(v int64) {
	o.Created = v
}

// GetCreatedBy returns the CreatedBy field value
func (o *ActionModel) GetCreatedBy() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value
// and a boolean to check if the value has been set.
func (o *ActionModel) GetCreatedByOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedBy, true
}

// SetCreatedBy sets field value
func (o *ActionModel) SetCreatedBy(v int64) {
	o.CreatedBy = v
}

// GetDescription returns the Description field value
func (o *ActionModel) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *ActionModel) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *ActionModel) SetDescription(v string) {
	o.Description = v
}

// GetDisabled returns the Disabled field value
func (o *ActionModel) GetDisabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Disabled
}

// GetDisabledOk returns a tuple with the Disabled field value
// and a boolean to check if the value has been set.
func (o *ActionModel) GetDisabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Disabled, true
}

// SetDisabled sets field value
func (o *ActionModel) SetDisabled(v bool) {
	o.Disabled = v
}

// GetEvent returns the Event field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ActionModel) GetEvent() TriggerEvent {
	if o == nil || IsNil(o.Event.Get()) {
		var ret TriggerEvent
		return ret
	}
	return *o.Event.Get()
}

// GetEventOk returns a tuple with the Event field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ActionModel) GetEventOk() (*TriggerEvent, bool) {
	if o == nil {
		return nil, false
	}
	return o.Event.Get(), o.Event.IsSet()
}

// HasEvent returns a boolean if a field has been set.
func (o *ActionModel) HasEvent() bool {
	if o != nil && o.Event.IsSet() {
		return true
	}

	return false
}

// SetEvent gets a reference to the given NullableTriggerEvent and assigns it to the Event field.
func (o *ActionModel) SetEvent(v TriggerEvent) {
	o.Event.Set(&v)
}

// SetEventNil sets the value for Event to be an explicit nil
func (o *ActionModel) SetEventNil() {
	o.Event.Set(nil)
}

// UnsetEvent ensures that no value is present for Event, not even an explicit nil
func (o *ActionModel) UnsetEvent() {
	o.Event.Unset()
}

// GetId returns the Id field value
func (o *ActionModel) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ActionModel) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ActionModel) SetId(v int64) {
	o.Id = v
}

// GetName returns the Name field value
func (o *ActionModel) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ActionModel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ActionModel) SetName(v string) {
	o.Name = v
}

// GetRepoId returns the RepoId field value
func (o *ActionModel) GetRepoId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.RepoId
}

// GetRepoIdOk returns a tuple with the RepoId field value
// and a boolean to check if the value has been set.
func (o *ActionModel) GetRepoIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RepoId, true
}

// SetRepoId sets field value
func (o *ActionModel) SetRepoId(v int64) {
	o.RepoId = v
}

// GetSeq returns the Seq field value
func (o *ActionModel) GetSeq() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Seq
}

// GetSeqOk returns a tuple with the Seq field value
// and a boolean to check if the value has been set.
func (o *ActionModel) GetSeqOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Seq, true
}

// SetSeq sets field value
func (o *ActionModel) SetSeq(v int64) {
	o.Seq = v
}

// GetUpdated returns the Updated field value
func (o *ActionModel) GetUpdated() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value
// and a boolean to check if the value has been set.
func (o *ActionModel) GetUpdatedOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Updated, true
}

// SetUpdated sets field value
func (o *ActionModel) SetUpdated(v int64) {
	o.Updated = v
}

// GetVersion returns the Version field value
func (o *ActionModel) GetVersion() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *ActionModel) GetVersionOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *ActionModel) SetVersion(v int64) {
	o.Version = v
}

// GetYamlPath returns the YamlPath field value
func (o *ActionModel) GetYamlPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.YamlPath
}

// GetYamlPathOk returns a tuple with the YamlPath field value
// and a boolean to check if the value has been set.
func (o *ActionModel) GetYamlPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.YamlPath, true
}

// SetYamlPath sets field value
func (o *ActionModel) SetYamlPath(v string) {
	o.YamlPath = v
}

// GetYamlProvider returns the YamlProvider field value
func (o *ActionModel) GetYamlProvider() WorkflowProvider {
	if o == nil {
		var ret WorkflowProvider
		return ret
	}

	return o.YamlProvider
}

// GetYamlProviderOk returns a tuple with the YamlProvider field value
// and a boolean to check if the value has been set.
func (o *ActionModel) GetYamlProviderOk() (*WorkflowProvider, bool) {
	if o == nil {
		return nil, false
	}
	return &o.YamlProvider, true
}

// SetYamlProvider sets field value
func (o *ActionModel) SetYamlProvider(v WorkflowProvider) {
	o.YamlProvider = v
}

func (o ActionModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ActionModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["created"] = o.Created
	toSerialize["created_by"] = o.CreatedBy
	toSerialize["description"] = o.Description
	toSerialize["disabled"] = o.Disabled
	if o.Event.IsSet() {
		toSerialize["event"] = o.Event.Get()
	}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["repo_id"] = o.RepoId
	toSerialize["seq"] = o.Seq
	toSerialize["updated"] = o.Updated
	toSerialize["version"] = o.Version
	toSerialize["yaml_path"] = o.YamlPath
	toSerialize["yaml_provider"] = o.YamlProvider
	return toSerialize, nil
}

func (o *ActionModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"created",
		"created_by",
		"description",
		"disabled",
		"id",
		"name",
		"repo_id",
		"seq",
		"updated",
		"version",
		"yaml_path",
		"yaml_provider",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varActionModel := _ActionModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varActionModel)

	if err != nil {
		return err
	}

	*o = ActionModel(varActionModel)

	return err
}

type NullableActionModel struct {
	value *ActionModel
	isSet bool
}

func (v NullableActionModel) Get() *ActionModel {
	return v.value
}

func (v *NullableActionModel) Set(val *ActionModel) {
	v.value = val
	v.isSet = true
}

func (v NullableActionModel) IsSet() bool {
	return v.isSet
}

func (v *NullableActionModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActionModel(val *ActionModel) *NullableActionModel {
	return &NullableActionModel{value: val, isSet: true}
}

func (v NullableActionModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActionModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
