/*
GitBundle API

GitBundle API documentation.

API version: 3.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbundlesdk

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PathDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PathDetails{}

// PathDetails struct for PathDetails
type PathDetails struct {
	LastCommit Commit `json:"last_commit"`
	Path       string `json:"path"`
}

type _PathDetails PathDetails

// NewPathDetails instantiates a new PathDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPathDetails(lastCommit Commit, path string) *PathDetails {
	this := PathDetails{}
	this.LastCommit = lastCommit
	this.Path = path
	return &this
}

// NewPathDetailsWithDefaults instantiates a new PathDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPathDetailsWithDefaults() *PathDetails {
	this := PathDetails{}
	return &this
}

// GetLastCommit returns the LastCommit field value
func (o *PathDetails) GetLastCommit() Commit {
	if o == nil {
		var ret Commit
		return ret
	}

	return o.LastCommit
}

// GetLastCommitOk returns a tuple with the LastCommit field value
// and a boolean to check if the value has been set.
func (o *PathDetails) GetLastCommitOk() (*Commit, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastCommit, true
}

// SetLastCommit sets field value
func (o *PathDetails) SetLastCommit(v Commit) {
	o.LastCommit = v
}

// GetPath returns the Path field value
func (o *PathDetails) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *PathDetails) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *PathDetails) SetPath(v string) {
	o.Path = v
}

func (o PathDetails) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PathDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["last_commit"] = o.LastCommit
	toSerialize["path"] = o.Path
	return toSerialize, nil
}

func (o *PathDetails) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"last_commit",
		"path",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPathDetails := _PathDetails{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPathDetails)

	if err != nil {
		return err
	}

	*o = PathDetails(varPathDetails)

	return err
}

type NullablePathDetails struct {
	value *PathDetails
	isSet bool
}

func (v NullablePathDetails) Get() *PathDetails {
	return v.value
}

func (v *NullablePathDetails) Set(val *PathDetails) {
	v.value = val
	v.isSet = true
}

func (v NullablePathDetails) IsSet() bool {
	return v.isSet
}

func (v *NullablePathDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePathDetails(val *PathDetails) *NullablePathDetails {
	return &NullablePathDetails{value: val, isSet: true}
}

func (v NullablePathDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePathDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
