/*
GitBundle API

GitBundle API documentation.

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbundlesdk

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the Heatmap type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Heatmap{}

// Heatmap struct for Heatmap
type Heatmap struct {
	Contributions []NumContributonWithDate `json:"contributions"`
	Years         []int32                  `json:"years"`
}

type _Heatmap Heatmap

// NewHeatmap instantiates a new Heatmap object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHeatmap(contributions []NumContributonWithDate, years []int32) *Heatmap {
	this := Heatmap{}
	this.Contributions = contributions
	this.Years = years
	return &this
}

// NewHeatmapWithDefaults instantiates a new Heatmap object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHeatmapWithDefaults() *Heatmap {
	this := Heatmap{}
	return &this
}

// GetContributions returns the Contributions field value
func (o *Heatmap) GetContributions() []NumContributonWithDate {
	if o == nil {
		var ret []NumContributonWithDate
		return ret
	}

	return o.Contributions
}

// GetContributionsOk returns a tuple with the Contributions field value
// and a boolean to check if the value has been set.
func (o *Heatmap) GetContributionsOk() ([]NumContributonWithDate, bool) {
	if o == nil {
		return nil, false
	}
	return o.Contributions, true
}

// SetContributions sets field value
func (o *Heatmap) SetContributions(v []NumContributonWithDate) {
	o.Contributions = v
}

// GetYears returns the Years field value
func (o *Heatmap) GetYears() []int32 {
	if o == nil {
		var ret []int32
		return ret
	}

	return o.Years
}

// GetYearsOk returns a tuple with the Years field value
// and a boolean to check if the value has been set.
func (o *Heatmap) GetYearsOk() ([]int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Years, true
}

// SetYears sets field value
func (o *Heatmap) SetYears(v []int32) {
	o.Years = v
}

func (o Heatmap) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Heatmap) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["contributions"] = o.Contributions
	toSerialize["years"] = o.Years
	return toSerialize, nil
}

func (o *Heatmap) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"contributions",
		"years",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHeatmap := _Heatmap{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHeatmap)

	if err != nil {
		return err
	}

	*o = Heatmap(varHeatmap)

	return err
}

type NullableHeatmap struct {
	value *Heatmap
	isSet bool
}

func (v NullableHeatmap) Get() *Heatmap {
	return v.value
}

func (v *NullableHeatmap) Set(val *Heatmap) {
	v.value = val
	v.isSet = true
}

func (v NullableHeatmap) IsSet() bool {
	return v.isSet
}

func (v *NullableHeatmap) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHeatmap(val *Heatmap) *NullableHeatmap {
	return &NullableHeatmap{value: val, isSet: true}
}

func (v NullableHeatmap) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHeatmap) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
