/*
GitBundle API

GitBundle API documentation.

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbundlesdk

import (
	"encoding/json"
)

// checks if the CommitDiffFile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommitDiffFile{}

// CommitDiffFile struct for CommitDiffFile
type CommitDiffFile struct {
	EndLine   *int64  `json:"end_line,omitempty"`
	Path      *string `json:"path,omitempty"`
	StartLine *int64  `json:"start_line,omitempty"`
}

// NewCommitDiffFile instantiates a new CommitDiffFile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommitDiffFile() *CommitDiffFile {
	this := CommitDiffFile{}
	return &this
}

// NewCommitDiffFileWithDefaults instantiates a new CommitDiffFile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommitDiffFileWithDefaults() *CommitDiffFile {
	this := CommitDiffFile{}
	return &this
}

// GetEndLine returns the EndLine field value if set, zero value otherwise.
func (o *CommitDiffFile) GetEndLine() int64 {
	if o == nil || IsNil(o.EndLine) {
		var ret int64
		return ret
	}
	return *o.EndLine
}

// GetEndLineOk returns a tuple with the EndLine field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommitDiffFile) GetEndLineOk() (*int64, bool) {
	if o == nil || IsNil(o.EndLine) {
		return nil, false
	}
	return o.EndLine, true
}

// HasEndLine returns a boolean if a field has been set.
func (o *CommitDiffFile) HasEndLine() bool {
	if o != nil && !IsNil(o.EndLine) {
		return true
	}

	return false
}

// SetEndLine gets a reference to the given int64 and assigns it to the EndLine field.
func (o *CommitDiffFile) SetEndLine(v int64) {
	o.EndLine = &v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *CommitDiffFile) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommitDiffFile) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *CommitDiffFile) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *CommitDiffFile) SetPath(v string) {
	o.Path = &v
}

// GetStartLine returns the StartLine field value if set, zero value otherwise.
func (o *CommitDiffFile) GetStartLine() int64 {
	if o == nil || IsNil(o.StartLine) {
		var ret int64
		return ret
	}
	return *o.StartLine
}

// GetStartLineOk returns a tuple with the StartLine field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommitDiffFile) GetStartLineOk() (*int64, bool) {
	if o == nil || IsNil(o.StartLine) {
		return nil, false
	}
	return o.StartLine, true
}

// HasStartLine returns a boolean if a field has been set.
func (o *CommitDiffFile) HasStartLine() bool {
	if o != nil && !IsNil(o.StartLine) {
		return true
	}

	return false
}

// SetStartLine gets a reference to the given int64 and assigns it to the StartLine field.
func (o *CommitDiffFile) SetStartLine(v int64) {
	o.StartLine = &v
}

func (o CommitDiffFile) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommitDiffFile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EndLine) {
		toSerialize["end_line"] = o.EndLine
	}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	if !IsNil(o.StartLine) {
		toSerialize["start_line"] = o.StartLine
	}
	return toSerialize, nil
}

type NullableCommitDiffFile struct {
	value *CommitDiffFile
	isSet bool
}

func (v NullableCommitDiffFile) Get() *CommitDiffFile {
	return v.value
}

func (v *NullableCommitDiffFile) Set(val *CommitDiffFile) {
	v.value = val
	v.isSet = true
}

func (v NullableCommitDiffFile) IsSet() bool {
	return v.isSet
}

func (v *NullableCommitDiffFile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommitDiffFile(val *CommitDiffFile) *NullableCommitDiffFile {
	return &NullableCommitDiffFile{value: val, isSet: true}
}

func (v NullableCommitDiffFile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommitDiffFile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
