/*
GitBundle API

GitBundle API documentation.

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbundlesdk

import (
	"encoding/json"
	"fmt"
)

// RunnerArchContext the model 'RunnerArchContext'
type RunnerArchContext string

// List of RunnerArchContext
const (
	RUNNERARCHCONTEXT_X86   RunnerArchContext = "x86"
	RUNNERARCHCONTEXT_X64   RunnerArchContext = "x64"
	RUNNERARCHCONTEXT_ARM   RunnerArchContext = "arm"
	RUNNERARCHCONTEXT_ARM64 RunnerArchContext = "arm64"
)

// All allowed values of RunnerArchContext enum
var AllowedRunnerArchContextEnumValues = []RunnerArchContext{
	"x86",
	"x64",
	"arm",
	"arm64",
}

func (v *RunnerArchContext) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := RunnerArchContext(value)
	for _, existing := range AllowedRunnerArchContextEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid RunnerArchContext", value)
}

// NewRunnerArchContextFromValue returns a pointer to a valid RunnerArchContext
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewRunnerArchContextFromValue(v string) (*RunnerArchContext, error) {
	ev := RunnerArchContext(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for RunnerArchContext: valid values are %v", v, AllowedRunnerArchContextEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v RunnerArchContext) IsValid() bool {
	for _, existing := range AllowedRunnerArchContextEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to RunnerArchContext value
func (v RunnerArchContext) Ptr() *RunnerArchContext {
	return &v
}

type NullableRunnerArchContext struct {
	value *RunnerArchContext
	isSet bool
}

func (v NullableRunnerArchContext) Get() *RunnerArchContext {
	return v.value
}

func (v *NullableRunnerArchContext) Set(val *RunnerArchContext) {
	v.value = val
	v.isSet = true
}

func (v NullableRunnerArchContext) IsSet() bool {
	return v.isSet
}

func (v *NullableRunnerArchContext) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRunnerArchContext(val *RunnerArchContext) *NullableRunnerArchContext {
	return &NullableRunnerArchContext{value: val, isSet: true}
}

func (v NullableRunnerArchContext) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRunnerArchContext) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
