/*
GitBundle API

GitBundle API documentation.

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbundlesdk

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the RepoImportInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RepoImportInput{}

// RepoImportInput struct for RepoImportInput
type RepoImportInput struct {
	Description  string       `json:"description"`
	Identifier   string       `json:"identifier"`
	IsPublic     bool         `json:"is_public"`
	ParentRef    string       `json:"parent_ref"`
	Provider     RepoProvider `json:"provider"`
	ProviderRepo string       `json:"provider_repo"`
}

type _RepoImportInput RepoImportInput

// NewRepoImportInput instantiates a new RepoImportInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRepoImportInput(description string, identifier string, isPublic bool, parentRef string, provider RepoProvider, providerRepo string) *RepoImportInput {
	this := RepoImportInput{}
	this.Description = description
	this.Identifier = identifier
	this.IsPublic = isPublic
	this.ParentRef = parentRef
	this.Provider = provider
	this.ProviderRepo = providerRepo
	return &this
}

// NewRepoImportInputWithDefaults instantiates a new RepoImportInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRepoImportInputWithDefaults() *RepoImportInput {
	this := RepoImportInput{}
	return &this
}

// GetDescription returns the Description field value
func (o *RepoImportInput) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *RepoImportInput) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *RepoImportInput) SetDescription(v string) {
	o.Description = v
}

// GetIdentifier returns the Identifier field value
func (o *RepoImportInput) GetIdentifier() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Identifier
}

// GetIdentifierOk returns a tuple with the Identifier field value
// and a boolean to check if the value has been set.
func (o *RepoImportInput) GetIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Identifier, true
}

// SetIdentifier sets field value
func (o *RepoImportInput) SetIdentifier(v string) {
	o.Identifier = v
}

// GetIsPublic returns the IsPublic field value
func (o *RepoImportInput) GetIsPublic() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsPublic
}

// GetIsPublicOk returns a tuple with the IsPublic field value
// and a boolean to check if the value has been set.
func (o *RepoImportInput) GetIsPublicOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsPublic, true
}

// SetIsPublic sets field value
func (o *RepoImportInput) SetIsPublic(v bool) {
	o.IsPublic = v
}

// GetParentRef returns the ParentRef field value
func (o *RepoImportInput) GetParentRef() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ParentRef
}

// GetParentRefOk returns a tuple with the ParentRef field value
// and a boolean to check if the value has been set.
func (o *RepoImportInput) GetParentRefOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ParentRef, true
}

// SetParentRef sets field value
func (o *RepoImportInput) SetParentRef(v string) {
	o.ParentRef = v
}

// GetProvider returns the Provider field value
func (o *RepoImportInput) GetProvider() RepoProvider {
	if o == nil {
		var ret RepoProvider
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *RepoImportInput) GetProviderOk() (*RepoProvider, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *RepoImportInput) SetProvider(v RepoProvider) {
	o.Provider = v
}

// GetProviderRepo returns the ProviderRepo field value
func (o *RepoImportInput) GetProviderRepo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProviderRepo
}

// GetProviderRepoOk returns a tuple with the ProviderRepo field value
// and a boolean to check if the value has been set.
func (o *RepoImportInput) GetProviderRepoOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProviderRepo, true
}

// SetProviderRepo sets field value
func (o *RepoImportInput) SetProviderRepo(v string) {
	o.ProviderRepo = v
}

func (o RepoImportInput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RepoImportInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["description"] = o.Description
	toSerialize["identifier"] = o.Identifier
	toSerialize["is_public"] = o.IsPublic
	toSerialize["parent_ref"] = o.ParentRef
	toSerialize["provider"] = o.Provider
	toSerialize["provider_repo"] = o.ProviderRepo
	return toSerialize, nil
}

func (o *RepoImportInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"description",
		"identifier",
		"is_public",
		"parent_ref",
		"provider",
		"provider_repo",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRepoImportInput := _RepoImportInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRepoImportInput)

	if err != nil {
		return err
	}

	*o = RepoImportInput(varRepoImportInput)

	return err
}

type NullableRepoImportInput struct {
	value *RepoImportInput
	isSet bool
}

func (v NullableRepoImportInput) Get() *RepoImportInput {
	return v.value
}

func (v *NullableRepoImportInput) Set(val *RepoImportInput) {
	v.value = val
	v.isSet = true
}

func (v NullableRepoImportInput) IsSet() bool {
	return v.isSet
}

func (v *NullableRepoImportInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRepoImportInput(val *RepoImportInput) *NullableRepoImportInput {
	return &NullableRepoImportInput{value: val, isSet: true}
}

func (v NullableRepoImportInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRepoImportInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
