/*
GitBundle API

GitBundle API documentation.

API version: 3.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbundlesdk

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PullreqAuthor type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PullreqAuthor{}

// PullreqAuthor struct for PullreqAuthor
type PullreqAuthor struct {
	Author NullableUserModel `json:"author,omitempty"`
	Model  PullreqModel      `json:"model"`
}

type _PullreqAuthor PullreqAuthor

// NewPullreqAuthor instantiates a new PullreqAuthor object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPullreqAuthor(model PullreqModel) *PullreqAuthor {
	this := PullreqAuthor{}
	this.Model = model
	return &this
}

// NewPullreqAuthorWithDefaults instantiates a new PullreqAuthor object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPullreqAuthorWithDefaults() *PullreqAuthor {
	this := PullreqAuthor{}
	return &this
}

// GetAuthor returns the Author field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PullreqAuthor) GetAuthor() UserModel {
	if o == nil || IsNil(o.Author.Get()) {
		var ret UserModel
		return ret
	}
	return *o.Author.Get()
}

// GetAuthorOk returns a tuple with the Author field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PullreqAuthor) GetAuthorOk() (*UserModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Author.Get(), o.Author.IsSet()
}

// HasAuthor returns a boolean if a field has been set.
func (o *PullreqAuthor) HasAuthor() bool {
	if o != nil && o.Author.IsSet() {
		return true
	}

	return false
}

// SetAuthor gets a reference to the given NullableUserModel and assigns it to the Author field.
func (o *PullreqAuthor) SetAuthor(v UserModel) {
	o.Author.Set(&v)
}

// SetAuthorNil sets the value for Author to be an explicit nil
func (o *PullreqAuthor) SetAuthorNil() {
	o.Author.Set(nil)
}

// UnsetAuthor ensures that no value is present for Author, not even an explicit nil
func (o *PullreqAuthor) UnsetAuthor() {
	o.Author.Unset()
}

// GetModel returns the Model field value
func (o *PullreqAuthor) GetModel() PullreqModel {
	if o == nil {
		var ret PullreqModel
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *PullreqAuthor) GetModelOk() (*PullreqModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *PullreqAuthor) SetModel(v PullreqModel) {
	o.Model = v
}

func (o PullreqAuthor) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PullreqAuthor) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Author.IsSet() {
		toSerialize["author"] = o.Author.Get()
	}
	toSerialize["model"] = o.Model
	return toSerialize, nil
}

func (o *PullreqAuthor) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"model",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPullreqAuthor := _PullreqAuthor{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPullreqAuthor)

	if err != nil {
		return err
	}

	*o = PullreqAuthor(varPullreqAuthor)

	return err
}

type NullablePullreqAuthor struct {
	value *PullreqAuthor
	isSet bool
}

func (v NullablePullreqAuthor) Get() *PullreqAuthor {
	return v.value
}

func (v *NullablePullreqAuthor) Set(val *PullreqAuthor) {
	v.value = val
	v.isSet = true
}

func (v NullablePullreqAuthor) IsSet() bool {
	return v.isSet
}

func (v *NullablePullreqAuthor) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePullreqAuthor(val *PullreqAuthor) *NullablePullreqAuthor {
	return &NullablePullreqAuthor{value: val, isSet: true}
}

func (v NullablePullreqAuthor) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePullreqAuthor) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
