/*
GitBundle API

GitBundle API documentation.

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbundlesdk

import (
	"encoding/json"
	"fmt"
)

// TriggerAction the model 'TriggerAction'
type TriggerAction string

// List of TriggerAction
const (
	TRIGGERACTION_NOOP TriggerAction = "noop"
	TRIGGERACTION_BRANCH_CREATED TriggerAction = "branch_created"
	TRIGGERACTION_BRANCH_UPDATED TriggerAction = "branch_updated"
	TRIGGERACTION_TAG_CREATED TriggerAction = "tag_created"
	TRIGGERACTION_TAG_UPDATED TriggerAction = "tag_updated"
	TRIGGERACTION_PULLREQ_CREATED TriggerAction = "pullreq_created"
	TRIGGERACTION_PULLREQ_REOPENED TriggerAction = "pullreq_reopened"
	TRIGGERACTION_PULLREQ_BRANCH_UPDATED TriggerAction = "pullreq_branch_updated"
	TRIGGERACTION_PULLREQ_CLOSED TriggerAction = "pullreq_closed"
	TRIGGERACTION_PULLREQ_MERGED TriggerAction = "pullreq_merged"
)

// All allowed values of TriggerAction enum
var AllowedTriggerActionEnumValues = []TriggerAction{
	"noop",
	"branch_created",
	"branch_updated",
	"tag_created",
	"tag_updated",
	"pullreq_created",
	"pullreq_reopened",
	"pullreq_branch_updated",
	"pullreq_closed",
	"pullreq_merged",
}

func (v *TriggerAction) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TriggerAction(value)
	for _, existing := range AllowedTriggerActionEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid TriggerAction", value)
}

// NewTriggerActionFromValue returns a pointer to a valid TriggerAction
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTriggerActionFromValue(v string) (*TriggerAction, error) {
	ev := TriggerAction(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TriggerAction: valid values are %v", v, AllowedTriggerActionEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TriggerAction) IsValid() bool {
	for _, existing := range AllowedTriggerActionEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to TriggerAction value
func (v TriggerAction) Ptr() *TriggerAction {
	return &v
}

type NullableTriggerAction struct {
	value *TriggerAction
	isSet bool
}

func (v NullableTriggerAction) Get() *TriggerAction {
	return v.value
}

func (v *NullableTriggerAction) Set(val *TriggerAction) {
	v.value = val
	v.isSet = true
}

func (v NullableTriggerAction) IsSet() bool {
	return v.isSet
}

func (v *NullableTriggerAction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTriggerAction(val *TriggerAction) *NullableTriggerAction {
	return &NullableTriggerAction{value: val, isSet: true}
}

func (v NullableTriggerAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTriggerAction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

