/*
GitBundle API

GitBundle API documentation.

API version: 3.4.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbundlesdk

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TwoFactorScratchTokenInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TwoFactorScratchTokenInput{}

// TwoFactorScratchTokenInput struct for TwoFactorScratchTokenInput
type TwoFactorScratchTokenInput struct {
	Token string `json:"token"`
}

type _TwoFactorScratchTokenInput TwoFactorScratchTokenInput

// NewTwoFactorScratchTokenInput instantiates a new TwoFactorScratchTokenInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTwoFactorScratchTokenInput(token string) *TwoFactorScratchTokenInput {
	this := TwoFactorScratchTokenInput{}
	this.Token = token
	return &this
}

// NewTwoFactorScratchTokenInputWithDefaults instantiates a new TwoFactorScratchTokenInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTwoFactorScratchTokenInputWithDefaults() *TwoFactorScratchTokenInput {
	this := TwoFactorScratchTokenInput{}
	return &this
}

// GetToken returns the Token field value
func (o *TwoFactorScratchTokenInput) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *TwoFactorScratchTokenInput) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *TwoFactorScratchTokenInput) SetToken(v string) {
	o.Token = v
}

func (o TwoFactorScratchTokenInput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TwoFactorScratchTokenInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["token"] = o.Token
	return toSerialize, nil
}

func (o *TwoFactorScratchTokenInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTwoFactorScratchTokenInput := _TwoFactorScratchTokenInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTwoFactorScratchTokenInput)

	if err != nil {
		return err
	}

	*o = TwoFactorScratchTokenInput(varTwoFactorScratchTokenInput)

	return err
}

type NullableTwoFactorScratchTokenInput struct {
	value *TwoFactorScratchTokenInput
	isSet bool
}

func (v NullableTwoFactorScratchTokenInput) Get() *TwoFactorScratchTokenInput {
	return v.value
}

func (v *NullableTwoFactorScratchTokenInput) Set(val *TwoFactorScratchTokenInput) {
	v.value = val
	v.isSet = true
}

func (v NullableTwoFactorScratchTokenInput) IsSet() bool {
	return v.isSet
}

func (v *NullableTwoFactorScratchTokenInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTwoFactorScratchTokenInput(val *TwoFactorScratchTokenInput) *NullableTwoFactorScratchTokenInput {
	return &NullableTwoFactorScratchTokenInput{value: val, isSet: true}
}

func (v NullableTwoFactorScratchTokenInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTwoFactorScratchTokenInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
