/*
GitBundle API

GitBundle API documentation.

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbundlesdk

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ReleaseCreator type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReleaseCreator{}

// ReleaseCreator struct for ReleaseCreator
type ReleaseCreator struct {
	Creator NullableUserModel `json:"creator,omitempty"`
	Model   ReleaseModel      `json:"model"`
}

type _ReleaseCreator ReleaseCreator

// NewReleaseCreator instantiates a new ReleaseCreator object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReleaseCreator(model ReleaseModel) *ReleaseCreator {
	this := ReleaseCreator{}
	this.Model = model
	return &this
}

// NewReleaseCreatorWithDefaults instantiates a new ReleaseCreator object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReleaseCreatorWithDefaults() *ReleaseCreator {
	this := ReleaseCreator{}
	return &this
}

// GetCreator returns the Creator field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReleaseCreator) GetCreator() UserModel {
	if o == nil || IsNil(o.Creator.Get()) {
		var ret UserModel
		return ret
	}
	return *o.Creator.Get()
}

// GetCreatorOk returns a tuple with the Creator field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReleaseCreator) GetCreatorOk() (*UserModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Creator.Get(), o.Creator.IsSet()
}

// HasCreator returns a boolean if a field has been set.
func (o *ReleaseCreator) HasCreator() bool {
	if o != nil && o.Creator.IsSet() {
		return true
	}

	return false
}

// SetCreator gets a reference to the given NullableUserModel and assigns it to the Creator field.
func (o *ReleaseCreator) SetCreator(v UserModel) {
	o.Creator.Set(&v)
}

// SetCreatorNil sets the value for Creator to be an explicit nil
func (o *ReleaseCreator) SetCreatorNil() {
	o.Creator.Set(nil)
}

// UnsetCreator ensures that no value is present for Creator, not even an explicit nil
func (o *ReleaseCreator) UnsetCreator() {
	o.Creator.Unset()
}

// GetModel returns the Model field value
func (o *ReleaseCreator) GetModel() ReleaseModel {
	if o == nil {
		var ret ReleaseModel
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *ReleaseCreator) GetModelOk() (*ReleaseModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *ReleaseCreator) SetModel(v ReleaseModel) {
	o.Model = v
}

func (o ReleaseCreator) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReleaseCreator) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Creator.IsSet() {
		toSerialize["creator"] = o.Creator.Get()
	}
	toSerialize["model"] = o.Model
	return toSerialize, nil
}

func (o *ReleaseCreator) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"model",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReleaseCreator := _ReleaseCreator{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varReleaseCreator)

	if err != nil {
		return err
	}

	*o = ReleaseCreator(varReleaseCreator)

	return err
}

type NullableReleaseCreator struct {
	value *ReleaseCreator
	isSet bool
}

func (v NullableReleaseCreator) Get() *ReleaseCreator {
	return v.value
}

func (v *NullableReleaseCreator) Set(val *ReleaseCreator) {
	v.value = val
	v.isSet = true
}

func (v NullableReleaseCreator) IsSet() bool {
	return v.isSet
}

func (v *NullableReleaseCreator) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReleaseCreator(val *ReleaseCreator) *NullableReleaseCreator {
	return &NullableReleaseCreator{value: val, isSet: true}
}

func (v NullableReleaseCreator) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReleaseCreator) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
