/*
GitBundle API

GitBundle API documentation.

API version: 3.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbundlesdk

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the Contributor type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Contributor{}

// Contributor struct for Contributor
type Contributor struct {
	DisplayName *string `json:"display_name,omitempty"`
	Email       string  `json:"email"`
	Id          int64   `json:"id"`
	Name        string  `json:"name"`
	NumCommits  int64   `json:"num_commits"`
}

type _Contributor Contributor

// NewContributor instantiates a new Contributor object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContributor(email string, id int64, name string, numCommits int64) *Contributor {
	this := Contributor{}
	this.Email = email
	this.Id = id
	this.Name = name
	this.NumCommits = numCommits
	return &this
}

// NewContributorWithDefaults instantiates a new Contributor object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContributorWithDefaults() *Contributor {
	this := Contributor{}
	return &this
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *Contributor) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Contributor) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *Contributor) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *Contributor) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetEmail returns the Email field value
func (o *Contributor) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *Contributor) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *Contributor) SetEmail(v string) {
	o.Email = v
}

// GetId returns the Id field value
func (o *Contributor) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Contributor) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Contributor) SetId(v int64) {
	o.Id = v
}

// GetName returns the Name field value
func (o *Contributor) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Contributor) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Contributor) SetName(v string) {
	o.Name = v
}

// GetNumCommits returns the NumCommits field value
func (o *Contributor) GetNumCommits() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.NumCommits
}

// GetNumCommitsOk returns a tuple with the NumCommits field value
// and a boolean to check if the value has been set.
func (o *Contributor) GetNumCommitsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NumCommits, true
}

// SetNumCommits sets field value
func (o *Contributor) SetNumCommits(v int64) {
	o.NumCommits = v
}

func (o Contributor) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Contributor) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DisplayName) {
		toSerialize["display_name"] = o.DisplayName
	}
	toSerialize["email"] = o.Email
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["num_commits"] = o.NumCommits
	return toSerialize, nil
}

func (o *Contributor) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
		"id",
		"name",
		"num_commits",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varContributor := _Contributor{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varContributor)

	if err != nil {
		return err
	}

	*o = Contributor(varContributor)

	return err
}

type NullableContributor struct {
	value *Contributor
	isSet bool
}

func (v NullableContributor) Get() *Contributor {
	return v.value
}

func (v *NullableContributor) Set(val *Contributor) {
	v.value = val
	v.isSet = true
}

func (v NullableContributor) IsSet() bool {
	return v.isSet
}

func (v *NullableContributor) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContributor(val *Contributor) *NullableContributor {
	return &NullableContributor{value: val, isSet: true}
}

func (v NullableContributor) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContributor) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
