/*
GitBundle API

GitBundle API documentation.

API version: 3.4.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbundlesdk

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TokenCreateOutput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokenCreateOutput{}

// TokenCreateOutput struct for TokenCreateOutput
type TokenCreateOutput struct {
	AccessToken string        `json:"access_token"`
	ExpiresAt   NullableInt64 `json:"expires_at,omitempty"`
	Model       TokenModel    `json:"model"`
}

type _TokenCreateOutput TokenCreateOutput

// NewTokenCreateOutput instantiates a new TokenCreateOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenCreateOutput(accessToken string, model TokenModel) *TokenCreateOutput {
	this := TokenCreateOutput{}
	this.AccessToken = accessToken
	this.Model = model
	return &this
}

// NewTokenCreateOutputWithDefaults instantiates a new TokenCreateOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenCreateOutputWithDefaults() *TokenCreateOutput {
	this := TokenCreateOutput{}
	return &this
}

// GetAccessToken returns the AccessToken field value
func (o *TokenCreateOutput) GetAccessToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessToken
}

// GetAccessTokenOk returns a tuple with the AccessToken field value
// and a boolean to check if the value has been set.
func (o *TokenCreateOutput) GetAccessTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessToken, true
}

// SetAccessToken sets field value
func (o *TokenCreateOutput) SetAccessToken(v string) {
	o.AccessToken = v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TokenCreateOutput) GetExpiresAt() int64 {
	if o == nil || IsNil(o.ExpiresAt.Get()) {
		var ret int64
		return ret
	}
	return *o.ExpiresAt.Get()
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TokenCreateOutput) GetExpiresAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpiresAt.Get(), o.ExpiresAt.IsSet()
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *TokenCreateOutput) HasExpiresAt() bool {
	if o != nil && o.ExpiresAt.IsSet() {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given NullableInt64 and assigns it to the ExpiresAt field.
func (o *TokenCreateOutput) SetExpiresAt(v int64) {
	o.ExpiresAt.Set(&v)
}

// SetExpiresAtNil sets the value for ExpiresAt to be an explicit nil
func (o *TokenCreateOutput) SetExpiresAtNil() {
	o.ExpiresAt.Set(nil)
}

// UnsetExpiresAt ensures that no value is present for ExpiresAt, not even an explicit nil
func (o *TokenCreateOutput) UnsetExpiresAt() {
	o.ExpiresAt.Unset()
}

// GetModel returns the Model field value
func (o *TokenCreateOutput) GetModel() TokenModel {
	if o == nil {
		var ret TokenModel
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *TokenCreateOutput) GetModelOk() (*TokenModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *TokenCreateOutput) SetModel(v TokenModel) {
	o.Model = v
}

func (o TokenCreateOutput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokenCreateOutput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["access_token"] = o.AccessToken
	if o.ExpiresAt.IsSet() {
		toSerialize["expires_at"] = o.ExpiresAt.Get()
	}
	toSerialize["model"] = o.Model
	return toSerialize, nil
}

func (o *TokenCreateOutput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"access_token",
		"model",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTokenCreateOutput := _TokenCreateOutput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTokenCreateOutput)

	if err != nil {
		return err
	}

	*o = TokenCreateOutput(varTokenCreateOutput)

	return err
}

type NullableTokenCreateOutput struct {
	value *TokenCreateOutput
	isSet bool
}

func (v NullableTokenCreateOutput) Get() *TokenCreateOutput {
	return v.value
}

func (v *NullableTokenCreateOutput) Set(val *TokenCreateOutput) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenCreateOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenCreateOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenCreateOutput(val *TokenCreateOutput) *NullableTokenCreateOutput {
	return &NullableTokenCreateOutput{value: val, isSet: true}
}

func (v NullableTokenCreateOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenCreateOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
