/*
GitBundle API

GitBundle API documentation.

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbundlesdk

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the RepoDirContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RepoDirContent{}

// RepoDirContent struct for RepoDirContent
type RepoDirContent struct {
	Entries []RepoContentInfo `json:"entries"`
}

type _RepoDirContent RepoDirContent

// NewRepoDirContent instantiates a new RepoDirContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRepoDirContent(entries []RepoContentInfo) *RepoDirContent {
	this := RepoDirContent{}
	this.Entries = entries
	return &this
}

// NewRepoDirContentWithDefaults instantiates a new RepoDirContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRepoDirContentWithDefaults() *RepoDirContent {
	this := RepoDirContent{}
	return &this
}

// GetEntries returns the Entries field value
func (o *RepoDirContent) GetEntries() []RepoContentInfo {
	if o == nil {
		var ret []RepoContentInfo
		return ret
	}

	return o.Entries
}

// GetEntriesOk returns a tuple with the Entries field value
// and a boolean to check if the value has been set.
func (o *RepoDirContent) GetEntriesOk() ([]RepoContentInfo, bool) {
	if o == nil {
		return nil, false
	}
	return o.Entries, true
}

// SetEntries sets field value
func (o *RepoDirContent) SetEntries(v []RepoContentInfo) {
	o.Entries = v
}

func (o RepoDirContent) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RepoDirContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["entries"] = o.Entries
	return toSerialize, nil
}

func (o *RepoDirContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"entries",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRepoDirContent := _RepoDirContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRepoDirContent)

	if err != nil {
		return err
	}

	*o = RepoDirContent(varRepoDirContent)

	return err
}

type NullableRepoDirContent struct {
	value *RepoDirContent
	isSet bool
}

func (v NullableRepoDirContent) Get() *RepoDirContent {
	return v.value
}

func (v *NullableRepoDirContent) Set(val *RepoDirContent) {
	v.value = val
	v.isSet = true
}

func (v NullableRepoDirContent) IsSet() bool {
	return v.isSet
}

func (v *NullableRepoDirContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRepoDirContent(val *RepoDirContent) *NullableRepoDirContent {
	return &NullableRepoDirContent{value: val, isSet: true}
}

func (v NullableRepoDirContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRepoDirContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
