/*
GitBundle API

GitBundle API documentation.

API version: 3.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbundlesdk

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CodeOwnersViolation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CodeOwnersViolation{}

// CodeOwnersViolation struct for CodeOwnersViolation
type CodeOwnersViolation struct {
	Code    CodeOwnerViolationCode `json:"code"`
	Message string                 `json:"message"`
	Params  []interface{}          `json:"params"`
}

type _CodeOwnersViolation CodeOwnersViolation

// NewCodeOwnersViolation instantiates a new CodeOwnersViolation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCodeOwnersViolation(code CodeOwnerViolationCode, message string, params []interface{}) *CodeOwnersViolation {
	this := CodeOwnersViolation{}
	this.Code = code
	this.Message = message
	this.Params = params
	return &this
}

// NewCodeOwnersViolationWithDefaults instantiates a new CodeOwnersViolation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCodeOwnersViolationWithDefaults() *CodeOwnersViolation {
	this := CodeOwnersViolation{}
	return &this
}

// GetCode returns the Code field value
func (o *CodeOwnersViolation) GetCode() CodeOwnerViolationCode {
	if o == nil {
		var ret CodeOwnerViolationCode
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *CodeOwnersViolation) GetCodeOk() (*CodeOwnerViolationCode, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *CodeOwnersViolation) SetCode(v CodeOwnerViolationCode) {
	o.Code = v
}

// GetMessage returns the Message field value
func (o *CodeOwnersViolation) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *CodeOwnersViolation) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *CodeOwnersViolation) SetMessage(v string) {
	o.Message = v
}

// GetParams returns the Params field value
func (o *CodeOwnersViolation) GetParams() []interface{} {
	if o == nil {
		var ret []interface{}
		return ret
	}

	return o.Params
}

// GetParamsOk returns a tuple with the Params field value
// and a boolean to check if the value has been set.
func (o *CodeOwnersViolation) GetParamsOk() ([]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Params, true
}

// SetParams sets field value
func (o *CodeOwnersViolation) SetParams(v []interface{}) {
	o.Params = v
}

func (o CodeOwnersViolation) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CodeOwnersViolation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["message"] = o.Message
	toSerialize["params"] = o.Params
	return toSerialize, nil
}

func (o *CodeOwnersViolation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
		"message",
		"params",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCodeOwnersViolation := _CodeOwnersViolation{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCodeOwnersViolation)

	if err != nil {
		return err
	}

	*o = CodeOwnersViolation(varCodeOwnersViolation)

	return err
}

type NullableCodeOwnersViolation struct {
	value *CodeOwnersViolation
	isSet bool
}

func (v NullableCodeOwnersViolation) Get() *CodeOwnersViolation {
	return v.value
}

func (v *NullableCodeOwnersViolation) Set(val *CodeOwnersViolation) {
	v.value = val
	v.isSet = true
}

func (v NullableCodeOwnersViolation) IsSet() bool {
	return v.isSet
}

func (v *NullableCodeOwnersViolation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCodeOwnersViolation(val *CodeOwnersViolation) *NullableCodeOwnersViolation {
	return &NullableCodeOwnersViolation{value: val, isSet: true}
}

func (v NullableCodeOwnersViolation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCodeOwnersViolation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
