/*
GitBundle API

GitBundle API documentation.

API version: 3.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbundlesdk

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TagCreateInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TagCreateInput{}

// TagCreateInput struct for TagCreateInput
type TagCreateInput struct {
	BypassRules bool   `json:"bypass_rules"`
	Message     string `json:"message"`
	Name        string `json:"name"`
	Target      string `json:"target"`
}

type _TagCreateInput TagCreateInput

// NewTagCreateInput instantiates a new TagCreateInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTagCreateInput(bypassRules bool, message string, name string, target string) *TagCreateInput {
	this := TagCreateInput{}
	this.BypassRules = bypassRules
	this.Message = message
	this.Name = name
	this.Target = target
	return &this
}

// NewTagCreateInputWithDefaults instantiates a new TagCreateInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTagCreateInputWithDefaults() *TagCreateInput {
	this := TagCreateInput{}
	return &this
}

// GetBypassRules returns the BypassRules field value
func (o *TagCreateInput) GetBypassRules() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.BypassRules
}

// GetBypassRulesOk returns a tuple with the BypassRules field value
// and a boolean to check if the value has been set.
func (o *TagCreateInput) GetBypassRulesOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BypassRules, true
}

// SetBypassRules sets field value
func (o *TagCreateInput) SetBypassRules(v bool) {
	o.BypassRules = v
}

// GetMessage returns the Message field value
func (o *TagCreateInput) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *TagCreateInput) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *TagCreateInput) SetMessage(v string) {
	o.Message = v
}

// GetName returns the Name field value
func (o *TagCreateInput) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *TagCreateInput) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TagCreateInput) SetName(v string) {
	o.Name = v
}

// GetTarget returns the Target field value
func (o *TagCreateInput) GetTarget() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Target
}

// GetTargetOk returns a tuple with the Target field value
// and a boolean to check if the value has been set.
func (o *TagCreateInput) GetTargetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Target, true
}

// SetTarget sets field value
func (o *TagCreateInput) SetTarget(v string) {
	o.Target = v
}

func (o TagCreateInput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TagCreateInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["bypass_rules"] = o.BypassRules
	toSerialize["message"] = o.Message
	toSerialize["name"] = o.Name
	toSerialize["target"] = o.Target
	return toSerialize, nil
}

func (o *TagCreateInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"bypass_rules",
		"message",
		"name",
		"target",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTagCreateInput := _TagCreateInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTagCreateInput)

	if err != nil {
		return err
	}

	*o = TagCreateInput(varTagCreateInput)

	return err
}

type NullableTagCreateInput struct {
	value *TagCreateInput
	isSet bool
}

func (v NullableTagCreateInput) Get() *TagCreateInput {
	return v.value
}

func (v *NullableTagCreateInput) Set(val *TagCreateInput) {
	v.value = val
	v.isSet = true
}

func (v NullableTagCreateInput) IsSet() bool {
	return v.isSet
}

func (v *NullableTagCreateInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTagCreateInput(val *TagCreateInput) *NullableTagCreateInput {
	return &NullableTagCreateInput{value: val, isSet: true}
}

func (v NullableTagCreateInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTagCreateInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
