/*
GitBundle API

GitBundle API documentation.

API version: 3.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbundlesdk

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TwoFactorPasscodeInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TwoFactorPasscodeInput{}

// TwoFactorPasscodeInput struct for TwoFactorPasscodeInput
type TwoFactorPasscodeInput struct {
	Passcode string `json:"passcode"`
}

type _TwoFactorPasscodeInput TwoFactorPasscodeInput

// NewTwoFactorPasscodeInput instantiates a new TwoFactorPasscodeInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTwoFactorPasscodeInput(passcode string) *TwoFactorPasscodeInput {
	this := TwoFactorPasscodeInput{}
	this.Passcode = passcode
	return &this
}

// NewTwoFactorPasscodeInputWithDefaults instantiates a new TwoFactorPasscodeInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTwoFactorPasscodeInputWithDefaults() *TwoFactorPasscodeInput {
	this := TwoFactorPasscodeInput{}
	return &this
}

// GetPasscode returns the Passcode field value
func (o *TwoFactorPasscodeInput) GetPasscode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Passcode
}

// GetPasscodeOk returns a tuple with the Passcode field value
// and a boolean to check if the value has been set.
func (o *TwoFactorPasscodeInput) GetPasscodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Passcode, true
}

// SetPasscode sets field value
func (o *TwoFactorPasscodeInput) SetPasscode(v string) {
	o.Passcode = v
}

func (o TwoFactorPasscodeInput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TwoFactorPasscodeInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["passcode"] = o.Passcode
	return toSerialize, nil
}

func (o *TwoFactorPasscodeInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"passcode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTwoFactorPasscodeInput := _TwoFactorPasscodeInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTwoFactorPasscodeInput)

	if err != nil {
		return err
	}

	*o = TwoFactorPasscodeInput(varTwoFactorPasscodeInput)

	return err
}

type NullableTwoFactorPasscodeInput struct {
	value *TwoFactorPasscodeInput
	isSet bool
}

func (v NullableTwoFactorPasscodeInput) Get() *TwoFactorPasscodeInput {
	return v.value
}

func (v *NullableTwoFactorPasscodeInput) Set(val *TwoFactorPasscodeInput) {
	v.value = val
	v.isSet = true
}

func (v NullableTwoFactorPasscodeInput) IsSet() bool {
	return v.isSet
}

func (v *NullableTwoFactorPasscodeInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTwoFactorPasscodeInput(val *TwoFactorPasscodeInput) *NullableTwoFactorPasscodeInput {
	return &NullableTwoFactorPasscodeInput{value: val, isSet: true}
}

func (v NullableTwoFactorPasscodeInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTwoFactorPasscodeInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
