/*
GitBundle API

GitBundle API documentation.

API version: 3.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbundlesdk

import (
	"encoding/json"
	"fmt"
)

// PublicKeySort the model 'PublicKeySort'
type PublicKeySort string

// List of PublicKeySort
const (
	PUBLICKEYSORT_NOOP    PublicKeySort = "noop"
	PUBLICKEYSORT_ID      PublicKeySort = "id"
	PUBLICKEYSORT_NAME    PublicKeySort = "name"
	PUBLICKEYSORT_CREATED PublicKeySort = "created"
)

// All allowed values of PublicKeySort enum
var AllowedPublicKeySortEnumValues = []PublicKeySort{
	"noop",
	"id",
	"name",
	"created",
}

func (v *PublicKeySort) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PublicKeySort(value)
	for _, existing := range AllowedPublicKeySortEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PublicKeySort", value)
}

// NewPublicKeySortFromValue returns a pointer to a valid PublicKeySort
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPublicKeySortFromValue(v string) (*PublicKeySort, error) {
	ev := PublicKeySort(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PublicKeySort: valid values are %v", v, AllowedPublicKeySortEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PublicKeySort) IsValid() bool {
	for _, existing := range AllowedPublicKeySortEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PublicKeySort value
func (v PublicKeySort) Ptr() *PublicKeySort {
	return &v
}

type NullablePublicKeySort struct {
	value *PublicKeySort
	isSet bool
}

func (v NullablePublicKeySort) Get() *PublicKeySort {
	return v.value
}

func (v *NullablePublicKeySort) Set(val *PublicKeySort) {
	v.value = val
	v.isSet = true
}

func (v NullablePublicKeySort) IsSet() bool {
	return v.isSet
}

func (v *NullablePublicKeySort) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublicKeySort(val *PublicKeySort) *NullablePublicKeySort {
	return &NullablePublicKeySort{value: val, isSet: true}
}

func (v NullablePublicKeySort) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublicKeySort) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
