/*
GitBundle API

GitBundle API documentation.

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbundlesdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CommitFilesOutput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommitFilesOutput{}

// CommitFilesOutput struct for CommitFilesOutput
type CommitFilesOutput struct {
	CommitSha string `json:"commit_sha"`
	DryRunRules bool `json:"dry_run_rules"`
	RuleChecks []RuleCheckResult `json:"rule_checks"`
}

type _CommitFilesOutput CommitFilesOutput

// NewCommitFilesOutput instantiates a new CommitFilesOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommitFilesOutput(commitSha string, dryRunRules bool, ruleChecks []RuleCheckResult) *CommitFilesOutput {
	this := CommitFilesOutput{}
	this.CommitSha = commitSha
	this.DryRunRules = dryRunRules
	this.RuleChecks = ruleChecks
	return &this
}

// NewCommitFilesOutputWithDefaults instantiates a new CommitFilesOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommitFilesOutputWithDefaults() *CommitFilesOutput {
	this := CommitFilesOutput{}
	return &this
}

// GetCommitSha returns the CommitSha field value
func (o *CommitFilesOutput) GetCommitSha() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CommitSha
}

// GetCommitShaOk returns a tuple with the CommitSha field value
// and a boolean to check if the value has been set.
func (o *CommitFilesOutput) GetCommitShaOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CommitSha, true
}

// SetCommitSha sets field value
func (o *CommitFilesOutput) SetCommitSha(v string) {
	o.CommitSha = v
}

// GetDryRunRules returns the DryRunRules field value
func (o *CommitFilesOutput) GetDryRunRules() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.DryRunRules
}

// GetDryRunRulesOk returns a tuple with the DryRunRules field value
// and a boolean to check if the value has been set.
func (o *CommitFilesOutput) GetDryRunRulesOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DryRunRules, true
}

// SetDryRunRules sets field value
func (o *CommitFilesOutput) SetDryRunRules(v bool) {
	o.DryRunRules = v
}

// GetRuleChecks returns the RuleChecks field value
func (o *CommitFilesOutput) GetRuleChecks() []RuleCheckResult {
	if o == nil {
		var ret []RuleCheckResult
		return ret
	}

	return o.RuleChecks
}

// GetRuleChecksOk returns a tuple with the RuleChecks field value
// and a boolean to check if the value has been set.
func (o *CommitFilesOutput) GetRuleChecksOk() ([]RuleCheckResult, bool) {
	if o == nil {
		return nil, false
	}
	return o.RuleChecks, true
}

// SetRuleChecks sets field value
func (o *CommitFilesOutput) SetRuleChecks(v []RuleCheckResult) {
	o.RuleChecks = v
}

func (o CommitFilesOutput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommitFilesOutput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["commit_sha"] = o.CommitSha
	toSerialize["dry_run_rules"] = o.DryRunRules
	toSerialize["rule_checks"] = o.RuleChecks
	return toSerialize, nil
}

func (o *CommitFilesOutput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"commit_sha",
		"dry_run_rules",
		"rule_checks",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCommitFilesOutput := _CommitFilesOutput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCommitFilesOutput)

	if err != nil {
		return err
	}

	*o = CommitFilesOutput(varCommitFilesOutput)

	return err
}

type NullableCommitFilesOutput struct {
	value *CommitFilesOutput
	isSet bool
}

func (v NullableCommitFilesOutput) Get() *CommitFilesOutput {
	return v.value
}

func (v *NullableCommitFilesOutput) Set(val *CommitFilesOutput) {
	v.value = val
	v.isSet = true
}

func (v NullableCommitFilesOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableCommitFilesOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommitFilesOutput(val *CommitFilesOutput) *NullableCommitFilesOutput {
	return &NullableCommitFilesOutput{value: val, isSet: true}
}

func (v NullableCommitFilesOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommitFilesOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


