/*
GitBundle API

GitBundle API documentation.

API version: 3.4.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbundlesdk

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the JobProgress type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobProgress{}

// JobProgress struct for JobProgress
type JobProgress struct {
	Failure  string   `json:"failure"`
	Progress int64    `json:"progress"`
	Result   string   `json:"result"`
	State    JobState `json:"state"`
}

type _JobProgress JobProgress

// NewJobProgress instantiates a new JobProgress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobProgress(failure string, progress int64, result string, state JobState) *JobProgress {
	this := JobProgress{}
	this.Failure = failure
	this.Progress = progress
	this.Result = result
	this.State = state
	return &this
}

// NewJobProgressWithDefaults instantiates a new JobProgress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobProgressWithDefaults() *JobProgress {
	this := JobProgress{}
	return &this
}

// GetFailure returns the Failure field value
func (o *JobProgress) GetFailure() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Failure
}

// GetFailureOk returns a tuple with the Failure field value
// and a boolean to check if the value has been set.
func (o *JobProgress) GetFailureOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Failure, true
}

// SetFailure sets field value
func (o *JobProgress) SetFailure(v string) {
	o.Failure = v
}

// GetProgress returns the Progress field value
func (o *JobProgress) GetProgress() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Progress
}

// GetProgressOk returns a tuple with the Progress field value
// and a boolean to check if the value has been set.
func (o *JobProgress) GetProgressOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Progress, true
}

// SetProgress sets field value
func (o *JobProgress) SetProgress(v int64) {
	o.Progress = v
}

// GetResult returns the Result field value
func (o *JobProgress) GetResult() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *JobProgress) GetResultOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *JobProgress) SetResult(v string) {
	o.Result = v
}

// GetState returns the State field value
func (o *JobProgress) GetState() JobState {
	if o == nil {
		var ret JobState
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *JobProgress) GetStateOk() (*JobState, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *JobProgress) SetState(v JobState) {
	o.State = v
}

func (o JobProgress) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobProgress) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["failure"] = o.Failure
	toSerialize["progress"] = o.Progress
	toSerialize["result"] = o.Result
	toSerialize["state"] = o.State
	return toSerialize, nil
}

func (o *JobProgress) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"failure",
		"progress",
		"result",
		"state",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJobProgress := _JobProgress{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJobProgress)

	if err != nil {
		return err
	}

	*o = JobProgress(varJobProgress)

	return err
}

type NullableJobProgress struct {
	value *JobProgress
	isSet bool
}

func (v NullableJobProgress) Get() *JobProgress {
	return v.value
}

func (v *NullableJobProgress) Set(val *JobProgress) {
	v.value = val
	v.isSet = true
}

func (v NullableJobProgress) IsSet() bool {
	return v.isSet
}

func (v *NullableJobProgress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobProgress(val *JobProgress) *NullableJobProgress {
	return &NullableJobProgress{value: val, isSet: true}
}

func (v NullableJobProgress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobProgress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
