/*
GitBundle API

GitBundle API documentation.

API version: 3.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbundlesdk

import (
	"encoding/json"
)

// checks if the PullreqActivityMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PullreqActivityMetadata{}

// PullreqActivityMetadata struct for PullreqActivityMetadata
type PullreqActivityMetadata struct {
	Suggestions NullablePullreqActivitySuggestionsMetadata `json:"suggestions,omitempty"`
}

// NewPullreqActivityMetadata instantiates a new PullreqActivityMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPullreqActivityMetadata() *PullreqActivityMetadata {
	this := PullreqActivityMetadata{}
	return &this
}

// NewPullreqActivityMetadataWithDefaults instantiates a new PullreqActivityMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPullreqActivityMetadataWithDefaults() *PullreqActivityMetadata {
	this := PullreqActivityMetadata{}
	return &this
}

// GetSuggestions returns the Suggestions field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PullreqActivityMetadata) GetSuggestions() PullreqActivitySuggestionsMetadata {
	if o == nil || IsNil(o.Suggestions.Get()) {
		var ret PullreqActivitySuggestionsMetadata
		return ret
	}
	return *o.Suggestions.Get()
}

// GetSuggestionsOk returns a tuple with the Suggestions field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PullreqActivityMetadata) GetSuggestionsOk() (*PullreqActivitySuggestionsMetadata, bool) {
	if o == nil {
		return nil, false
	}
	return o.Suggestions.Get(), o.Suggestions.IsSet()
}

// HasSuggestions returns a boolean if a field has been set.
func (o *PullreqActivityMetadata) HasSuggestions() bool {
	if o != nil && o.Suggestions.IsSet() {
		return true
	}

	return false
}

// SetSuggestions gets a reference to the given NullablePullreqActivitySuggestionsMetadata and assigns it to the Suggestions field.
func (o *PullreqActivityMetadata) SetSuggestions(v PullreqActivitySuggestionsMetadata) {
	o.Suggestions.Set(&v)
}

// SetSuggestionsNil sets the value for Suggestions to be an explicit nil
func (o *PullreqActivityMetadata) SetSuggestionsNil() {
	o.Suggestions.Set(nil)
}

// UnsetSuggestions ensures that no value is present for Suggestions, not even an explicit nil
func (o *PullreqActivityMetadata) UnsetSuggestions() {
	o.Suggestions.Unset()
}

func (o PullreqActivityMetadata) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PullreqActivityMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Suggestions.IsSet() {
		toSerialize["suggestions"] = o.Suggestions.Get()
	}
	return toSerialize, nil
}

type NullablePullreqActivityMetadata struct {
	value *PullreqActivityMetadata
	isSet bool
}

func (v NullablePullreqActivityMetadata) Get() *PullreqActivityMetadata {
	return v.value
}

func (v *NullablePullreqActivityMetadata) Set(val *PullreqActivityMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullablePullreqActivityMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullablePullreqActivityMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePullreqActivityMetadata(val *PullreqActivityMetadata) *NullablePullreqActivityMetadata {
	return &NullablePullreqActivityMetadata{value: val, isSet: true}
}

func (v NullablePullreqActivityMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePullreqActivityMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
