/*
GitBundle API

GitBundle API documentation.

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbundlesdk

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the RunnerPatchInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RunnerPatchInput{}

// RunnerPatchInput struct for RunnerPatchInput
type RunnerPatchInput struct {
	Description string `json:"description"`
}

type _RunnerPatchInput RunnerPatchInput

// NewRunnerPatchInput instantiates a new RunnerPatchInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRunnerPatchInput(description string) *RunnerPatchInput {
	this := RunnerPatchInput{}
	this.Description = description
	return &this
}

// NewRunnerPatchInputWithDefaults instantiates a new RunnerPatchInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRunnerPatchInputWithDefaults() *RunnerPatchInput {
	this := RunnerPatchInput{}
	return &this
}

// GetDescription returns the Description field value
func (o *RunnerPatchInput) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *RunnerPatchInput) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *RunnerPatchInput) SetDescription(v string) {
	o.Description = v
}

func (o RunnerPatchInput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RunnerPatchInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["description"] = o.Description
	return toSerialize, nil
}

func (o *RunnerPatchInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"description",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRunnerPatchInput := _RunnerPatchInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRunnerPatchInput)

	if err != nil {
		return err
	}

	*o = RunnerPatchInput(varRunnerPatchInput)

	return err
}

type NullableRunnerPatchInput struct {
	value *RunnerPatchInput
	isSet bool
}

func (v NullableRunnerPatchInput) Get() *RunnerPatchInput {
	return v.value
}

func (v *NullableRunnerPatchInput) Set(val *RunnerPatchInput) {
	v.value = val
	v.isSet = true
}

func (v NullableRunnerPatchInput) IsSet() bool {
	return v.isSet
}

func (v *NullableRunnerPatchInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRunnerPatchInput(val *RunnerPatchInput) *NullableRunnerPatchInput {
	return &NullableRunnerPatchInput{value: val, isSet: true}
}

func (v NullableRunnerPatchInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRunnerPatchInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
