/*
GitBundle API

GitBundle API documentation.

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbundlesdk

import (
	"encoding/json"
)

// checks if the PageOption type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PageOption{}

// PageOption struct for PageOption
type PageOption struct {
	Page *int64 `json:"page,omitempty"`
	Size *int64 `json:"size,omitempty"`
}

// NewPageOption instantiates a new PageOption object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPageOption() *PageOption {
	this := PageOption{}
	return &this
}

// NewPageOptionWithDefaults instantiates a new PageOption object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPageOptionWithDefaults() *PageOption {
	this := PageOption{}
	return &this
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *PageOption) GetPage() int64 {
	if o == nil || IsNil(o.Page) {
		var ret int64
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PageOption) GetPageOk() (*int64, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *PageOption) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given int64 and assigns it to the Page field.
func (o *PageOption) SetPage(v int64) {
	o.Page = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *PageOption) GetSize() int64 {
	if o == nil || IsNil(o.Size) {
		var ret int64
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PageOption) GetSizeOk() (*int64, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *PageOption) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int64 and assigns it to the Size field.
func (o *PageOption) SetSize(v int64) {
	o.Size = &v
}

func (o PageOption) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PageOption) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	return toSerialize, nil
}

type NullablePageOption struct {
	value *PageOption
	isSet bool
}

func (v NullablePageOption) Get() *PageOption {
	return v.value
}

func (v *NullablePageOption) Set(val *PageOption) {
	v.value = val
	v.isSet = true
}

func (v NullablePageOption) IsSet() bool {
	return v.isSet
}

func (v *NullablePageOption) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePageOption(val *PageOption) *NullablePageOption {
	return &NullablePageOption{value: val, isSet: true}
}

func (v NullablePageOption) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePageOption) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


