/*
GitBundle API

GitBundle API documentation.

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbundlesdk

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DiffFileContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DiffFileContent{}

// DiffFileContent struct for DiffFileContent
type DiffFileContent struct {
	Header NullableString     `json:"header,omitempty"`
	Hunk   NullableHunkHeader `json:"hunk,omitempty"`
	Lines  []string           `json:"lines"`
}

type _DiffFileContent DiffFileContent

// NewDiffFileContent instantiates a new DiffFileContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDiffFileContent(lines []string) *DiffFileContent {
	this := DiffFileContent{}
	this.Lines = lines
	return &this
}

// NewDiffFileContentWithDefaults instantiates a new DiffFileContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDiffFileContentWithDefaults() *DiffFileContent {
	this := DiffFileContent{}
	return &this
}

// GetHeader returns the Header field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DiffFileContent) GetHeader() string {
	if o == nil || IsNil(o.Header.Get()) {
		var ret string
		return ret
	}
	return *o.Header.Get()
}

// GetHeaderOk returns a tuple with the Header field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DiffFileContent) GetHeaderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Header.Get(), o.Header.IsSet()
}

// HasHeader returns a boolean if a field has been set.
func (o *DiffFileContent) HasHeader() bool {
	if o != nil && o.Header.IsSet() {
		return true
	}

	return false
}

// SetHeader gets a reference to the given NullableString and assigns it to the Header field.
func (o *DiffFileContent) SetHeader(v string) {
	o.Header.Set(&v)
}

// SetHeaderNil sets the value for Header to be an explicit nil
func (o *DiffFileContent) SetHeaderNil() {
	o.Header.Set(nil)
}

// UnsetHeader ensures that no value is present for Header, not even an explicit nil
func (o *DiffFileContent) UnsetHeader() {
	o.Header.Unset()
}

// GetHunk returns the Hunk field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DiffFileContent) GetHunk() HunkHeader {
	if o == nil || IsNil(o.Hunk.Get()) {
		var ret HunkHeader
		return ret
	}
	return *o.Hunk.Get()
}

// GetHunkOk returns a tuple with the Hunk field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DiffFileContent) GetHunkOk() (*HunkHeader, bool) {
	if o == nil {
		return nil, false
	}
	return o.Hunk.Get(), o.Hunk.IsSet()
}

// HasHunk returns a boolean if a field has been set.
func (o *DiffFileContent) HasHunk() bool {
	if o != nil && o.Hunk.IsSet() {
		return true
	}

	return false
}

// SetHunk gets a reference to the given NullableHunkHeader and assigns it to the Hunk field.
func (o *DiffFileContent) SetHunk(v HunkHeader) {
	o.Hunk.Set(&v)
}

// SetHunkNil sets the value for Hunk to be an explicit nil
func (o *DiffFileContent) SetHunkNil() {
	o.Hunk.Set(nil)
}

// UnsetHunk ensures that no value is present for Hunk, not even an explicit nil
func (o *DiffFileContent) UnsetHunk() {
	o.Hunk.Unset()
}

// GetLines returns the Lines field value
func (o *DiffFileContent) GetLines() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Lines
}

// GetLinesOk returns a tuple with the Lines field value
// and a boolean to check if the value has been set.
func (o *DiffFileContent) GetLinesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Lines, true
}

// SetLines sets field value
func (o *DiffFileContent) SetLines(v []string) {
	o.Lines = v
}

func (o DiffFileContent) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DiffFileContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Header.IsSet() {
		toSerialize["header"] = o.Header.Get()
	}
	if o.Hunk.IsSet() {
		toSerialize["hunk"] = o.Hunk.Get()
	}
	toSerialize["lines"] = o.Lines
	return toSerialize, nil
}

func (o *DiffFileContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"lines",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDiffFileContent := _DiffFileContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDiffFileContent)

	if err != nil {
		return err
	}

	*o = DiffFileContent(varDiffFileContent)

	return err
}

type NullableDiffFileContent struct {
	value *DiffFileContent
	isSet bool
}

func (v NullableDiffFileContent) Get() *DiffFileContent {
	return v.value
}

func (v *NullableDiffFileContent) Set(val *DiffFileContent) {
	v.value = val
	v.isSet = true
}

func (v NullableDiffFileContent) IsSet() bool {
	return v.isSet
}

func (v *NullableDiffFileContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDiffFileContent(val *DiffFileContent) *NullableDiffFileContent {
	return &NullableDiffFileContent{value: val, isSet: true}
}

func (v NullableDiffFileContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDiffFileContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
