/*
GitBundle API

GitBundle API documentation.

API version: 3.4.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbundlesdk

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PasswordForgotInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PasswordForgotInput{}

// PasswordForgotInput struct for PasswordForgotInput
type PasswordForgotInput struct {
	Email string `json:"email"`
}

type _PasswordForgotInput PasswordForgotInput

// NewPasswordForgotInput instantiates a new PasswordForgotInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPasswordForgotInput(email string) *PasswordForgotInput {
	this := PasswordForgotInput{}
	this.Email = email
	return &this
}

// NewPasswordForgotInputWithDefaults instantiates a new PasswordForgotInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPasswordForgotInputWithDefaults() *PasswordForgotInput {
	this := PasswordForgotInput{}
	return &this
}

// GetEmail returns the Email field value
func (o *PasswordForgotInput) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *PasswordForgotInput) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *PasswordForgotInput) SetEmail(v string) {
	o.Email = v
}

func (o PasswordForgotInput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PasswordForgotInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	return toSerialize, nil
}

func (o *PasswordForgotInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPasswordForgotInput := _PasswordForgotInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPasswordForgotInput)

	if err != nil {
		return err
	}

	*o = PasswordForgotInput(varPasswordForgotInput)

	return err
}

type NullablePasswordForgotInput struct {
	value *PasswordForgotInput
	isSet bool
}

func (v NullablePasswordForgotInput) Get() *PasswordForgotInput {
	return v.value
}

func (v *NullablePasswordForgotInput) Set(val *PasswordForgotInput) {
	v.value = val
	v.isSet = true
}

func (v NullablePasswordForgotInput) IsSet() bool {
	return v.isSet
}

func (v *NullablePasswordForgotInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePasswordForgotInput(val *PasswordForgotInput) *NullablePasswordForgotInput {
	return &NullablePasswordForgotInput{value: val, isSet: true}
}

func (v NullablePasswordForgotInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePasswordForgotInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
