/*
GitBundle API

GitBundle API documentation.

API version: 3.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbundlesdk

import (
	"encoding/json"
)

// checks if the CreatedOption type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatedOption{}

// CreatedOption struct for CreatedOption
type CreatedOption struct {
	CreatedGt NullableInt64 `json:"created_gt,omitempty"`
	CreatedLt NullableInt64 `json:"created_lt,omitempty"`
}

// NewCreatedOption instantiates a new CreatedOption object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatedOption() *CreatedOption {
	this := CreatedOption{}
	return &this
}

// NewCreatedOptionWithDefaults instantiates a new CreatedOption object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatedOptionWithDefaults() *CreatedOption {
	this := CreatedOption{}
	return &this
}

// GetCreatedGt returns the CreatedGt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreatedOption) GetCreatedGt() int64 {
	if o == nil || IsNil(o.CreatedGt.Get()) {
		var ret int64
		return ret
	}
	return *o.CreatedGt.Get()
}

// GetCreatedGtOk returns a tuple with the CreatedGt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreatedOption) GetCreatedGtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedGt.Get(), o.CreatedGt.IsSet()
}

// HasCreatedGt returns a boolean if a field has been set.
func (o *CreatedOption) HasCreatedGt() bool {
	if o != nil && o.CreatedGt.IsSet() {
		return true
	}

	return false
}

// SetCreatedGt gets a reference to the given NullableInt64 and assigns it to the CreatedGt field.
func (o *CreatedOption) SetCreatedGt(v int64) {
	o.CreatedGt.Set(&v)
}

// SetCreatedGtNil sets the value for CreatedGt to be an explicit nil
func (o *CreatedOption) SetCreatedGtNil() {
	o.CreatedGt.Set(nil)
}

// UnsetCreatedGt ensures that no value is present for CreatedGt, not even an explicit nil
func (o *CreatedOption) UnsetCreatedGt() {
	o.CreatedGt.Unset()
}

// GetCreatedLt returns the CreatedLt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreatedOption) GetCreatedLt() int64 {
	if o == nil || IsNil(o.CreatedLt.Get()) {
		var ret int64
		return ret
	}
	return *o.CreatedLt.Get()
}

// GetCreatedLtOk returns a tuple with the CreatedLt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreatedOption) GetCreatedLtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedLt.Get(), o.CreatedLt.IsSet()
}

// HasCreatedLt returns a boolean if a field has been set.
func (o *CreatedOption) HasCreatedLt() bool {
	if o != nil && o.CreatedLt.IsSet() {
		return true
	}

	return false
}

// SetCreatedLt gets a reference to the given NullableInt64 and assigns it to the CreatedLt field.
func (o *CreatedOption) SetCreatedLt(v int64) {
	o.CreatedLt.Set(&v)
}

// SetCreatedLtNil sets the value for CreatedLt to be an explicit nil
func (o *CreatedOption) SetCreatedLtNil() {
	o.CreatedLt.Set(nil)
}

// UnsetCreatedLt ensures that no value is present for CreatedLt, not even an explicit nil
func (o *CreatedOption) UnsetCreatedLt() {
	o.CreatedLt.Unset()
}

func (o CreatedOption) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatedOption) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.CreatedGt.IsSet() {
		toSerialize["created_gt"] = o.CreatedGt.Get()
	}
	if o.CreatedLt.IsSet() {
		toSerialize["created_lt"] = o.CreatedLt.Get()
	}
	return toSerialize, nil
}

type NullableCreatedOption struct {
	value *CreatedOption
	isSet bool
}

func (v NullableCreatedOption) Get() *CreatedOption {
	return v.value
}

func (v *NullableCreatedOption) Set(val *CreatedOption) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatedOption) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatedOption) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatedOption(val *CreatedOption) *NullableCreatedOption {
	return &NullableCreatedOption{value: val, isSet: true}
}

func (v NullableCreatedOption) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatedOption) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
