/*
GitBundle API

GitBundle API documentation.

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbundlesdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TriggerModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TriggerModel{}

// TriggerModel struct for TriggerModel
type TriggerModel struct {
	ActionId int64 `json:"action_id"`
	Actions []TriggerAction `json:"actions"`
	Created int64 `json:"created"`
	CreatedBy int64 `json:"created_by"`
	Description string `json:"description"`
	Disabled bool `json:"disabled"`
	Id int64 `json:"id"`
	Name string `json:"name"`
	RepoId int64 `json:"repo_id"`
	Secret string `json:"secret"`
	Type string `json:"type"`
	Updated int64 `json:"updated"`
	Version int64 `json:"version"`
}

type _TriggerModel TriggerModel

// NewTriggerModel instantiates a new TriggerModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTriggerModel(actionId int64, actions []TriggerAction, created int64, createdBy int64, description string, disabled bool, id int64, name string, repoId int64, secret string, type_ string, updated int64, version int64) *TriggerModel {
	this := TriggerModel{}
	this.ActionId = actionId
	this.Actions = actions
	this.Created = created
	this.CreatedBy = createdBy
	this.Description = description
	this.Disabled = disabled
	this.Id = id
	this.Name = name
	this.RepoId = repoId
	this.Secret = secret
	this.Type = type_
	this.Updated = updated
	this.Version = version
	return &this
}

// NewTriggerModelWithDefaults instantiates a new TriggerModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTriggerModelWithDefaults() *TriggerModel {
	this := TriggerModel{}
	return &this
}

// GetActionId returns the ActionId field value
func (o *TriggerModel) GetActionId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ActionId
}

// GetActionIdOk returns a tuple with the ActionId field value
// and a boolean to check if the value has been set.
func (o *TriggerModel) GetActionIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ActionId, true
}

// SetActionId sets field value
func (o *TriggerModel) SetActionId(v int64) {
	o.ActionId = v
}

// GetActions returns the Actions field value
func (o *TriggerModel) GetActions() []TriggerAction {
	if o == nil {
		var ret []TriggerAction
		return ret
	}

	return o.Actions
}

// GetActionsOk returns a tuple with the Actions field value
// and a boolean to check if the value has been set.
func (o *TriggerModel) GetActionsOk() ([]TriggerAction, bool) {
	if o == nil {
		return nil, false
	}
	return o.Actions, true
}

// SetActions sets field value
func (o *TriggerModel) SetActions(v []TriggerAction) {
	o.Actions = v
}

// GetCreated returns the Created field value
func (o *TriggerModel) GetCreated() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *TriggerModel) GetCreatedOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *TriggerModel) SetCreated(v int64) {
	o.Created = v
}

// GetCreatedBy returns the CreatedBy field value
func (o *TriggerModel) GetCreatedBy() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value
// and a boolean to check if the value has been set.
func (o *TriggerModel) GetCreatedByOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedBy, true
}

// SetCreatedBy sets field value
func (o *TriggerModel) SetCreatedBy(v int64) {
	o.CreatedBy = v
}

// GetDescription returns the Description field value
func (o *TriggerModel) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *TriggerModel) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *TriggerModel) SetDescription(v string) {
	o.Description = v
}

// GetDisabled returns the Disabled field value
func (o *TriggerModel) GetDisabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Disabled
}

// GetDisabledOk returns a tuple with the Disabled field value
// and a boolean to check if the value has been set.
func (o *TriggerModel) GetDisabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Disabled, true
}

// SetDisabled sets field value
func (o *TriggerModel) SetDisabled(v bool) {
	o.Disabled = v
}

// GetId returns the Id field value
func (o *TriggerModel) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *TriggerModel) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *TriggerModel) SetId(v int64) {
	o.Id = v
}

// GetName returns the Name field value
func (o *TriggerModel) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *TriggerModel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TriggerModel) SetName(v string) {
	o.Name = v
}

// GetRepoId returns the RepoId field value
func (o *TriggerModel) GetRepoId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.RepoId
}

// GetRepoIdOk returns a tuple with the RepoId field value
// and a boolean to check if the value has been set.
func (o *TriggerModel) GetRepoIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RepoId, true
}

// SetRepoId sets field value
func (o *TriggerModel) SetRepoId(v int64) {
	o.RepoId = v
}

// GetSecret returns the Secret field value
func (o *TriggerModel) GetSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Secret
}

// GetSecretOk returns a tuple with the Secret field value
// and a boolean to check if the value has been set.
func (o *TriggerModel) GetSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Secret, true
}

// SetSecret sets field value
func (o *TriggerModel) SetSecret(v string) {
	o.Secret = v
}

// GetType returns the Type field value
func (o *TriggerModel) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TriggerModel) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TriggerModel) SetType(v string) {
	o.Type = v
}

// GetUpdated returns the Updated field value
func (o *TriggerModel) GetUpdated() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value
// and a boolean to check if the value has been set.
func (o *TriggerModel) GetUpdatedOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Updated, true
}

// SetUpdated sets field value
func (o *TriggerModel) SetUpdated(v int64) {
	o.Updated = v
}

// GetVersion returns the Version field value
func (o *TriggerModel) GetVersion() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *TriggerModel) GetVersionOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *TriggerModel) SetVersion(v int64) {
	o.Version = v
}

func (o TriggerModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TriggerModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action_id"] = o.ActionId
	toSerialize["actions"] = o.Actions
	toSerialize["created"] = o.Created
	toSerialize["created_by"] = o.CreatedBy
	toSerialize["description"] = o.Description
	toSerialize["disabled"] = o.Disabled
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["repo_id"] = o.RepoId
	toSerialize["secret"] = o.Secret
	toSerialize["type"] = o.Type
	toSerialize["updated"] = o.Updated
	toSerialize["version"] = o.Version
	return toSerialize, nil
}

func (o *TriggerModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"action_id",
		"actions",
		"created",
		"created_by",
		"description",
		"disabled",
		"id",
		"name",
		"repo_id",
		"secret",
		"type",
		"updated",
		"version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTriggerModel := _TriggerModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTriggerModel)

	if err != nil {
		return err
	}

	*o = TriggerModel(varTriggerModel)

	return err
}

type NullableTriggerModel struct {
	value *TriggerModel
	isSet bool
}

func (v NullableTriggerModel) Get() *TriggerModel {
	return v.value
}

func (v *NullableTriggerModel) Set(val *TriggerModel) {
	v.value = val
	v.isSet = true
}

func (v NullableTriggerModel) IsSet() bool {
	return v.isSet
}

func (v *NullableTriggerModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTriggerModel(val *TriggerModel) *NullableTriggerModel {
	return &NullableTriggerModel{value: val, isSet: true}
}

func (v NullableTriggerModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTriggerModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


