/*
GitBundle API

GitBundle API documentation.

API version: 3.3.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbundlesdk

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the RegisterTokenModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegisterTokenModel{}

// RegisterTokenModel struct for RegisterTokenModel
type RegisterTokenModel struct {
	Created   int64  `json:"created"`
	CreatedBy int64  `json:"created_by"`
	Id        int64  `json:"id"`
	ParentId  int64  `json:"parent_id"`
	Scope     Scope  `json:"scope"`
	Token     string `json:"token"`
	Updated   int64  `json:"updated"`
	Version   int64  `json:"version"`
}

type _RegisterTokenModel RegisterTokenModel

// NewRegisterTokenModel instantiates a new RegisterTokenModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegisterTokenModel(created int64, createdBy int64, id int64, parentId int64, scope Scope, token string, updated int64, version int64) *RegisterTokenModel {
	this := RegisterTokenModel{}
	this.Created = created
	this.CreatedBy = createdBy
	this.Id = id
	this.ParentId = parentId
	this.Scope = scope
	this.Token = token
	this.Updated = updated
	this.Version = version
	return &this
}

// NewRegisterTokenModelWithDefaults instantiates a new RegisterTokenModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegisterTokenModelWithDefaults() *RegisterTokenModel {
	this := RegisterTokenModel{}
	return &this
}

// GetCreated returns the Created field value
func (o *RegisterTokenModel) GetCreated() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *RegisterTokenModel) GetCreatedOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *RegisterTokenModel) SetCreated(v int64) {
	o.Created = v
}

// GetCreatedBy returns the CreatedBy field value
func (o *RegisterTokenModel) GetCreatedBy() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value
// and a boolean to check if the value has been set.
func (o *RegisterTokenModel) GetCreatedByOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedBy, true
}

// SetCreatedBy sets field value
func (o *RegisterTokenModel) SetCreatedBy(v int64) {
	o.CreatedBy = v
}

// GetId returns the Id field value
func (o *RegisterTokenModel) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RegisterTokenModel) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RegisterTokenModel) SetId(v int64) {
	o.Id = v
}

// GetParentId returns the ParentId field value
func (o *RegisterTokenModel) GetParentId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ParentId
}

// GetParentIdOk returns a tuple with the ParentId field value
// and a boolean to check if the value has been set.
func (o *RegisterTokenModel) GetParentIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ParentId, true
}

// SetParentId sets field value
func (o *RegisterTokenModel) SetParentId(v int64) {
	o.ParentId = v
}

// GetScope returns the Scope field value
func (o *RegisterTokenModel) GetScope() Scope {
	if o == nil {
		var ret Scope
		return ret
	}

	return o.Scope
}

// GetScopeOk returns a tuple with the Scope field value
// and a boolean to check if the value has been set.
func (o *RegisterTokenModel) GetScopeOk() (*Scope, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Scope, true
}

// SetScope sets field value
func (o *RegisterTokenModel) SetScope(v Scope) {
	o.Scope = v
}

// GetToken returns the Token field value
func (o *RegisterTokenModel) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *RegisterTokenModel) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *RegisterTokenModel) SetToken(v string) {
	o.Token = v
}

// GetUpdated returns the Updated field value
func (o *RegisterTokenModel) GetUpdated() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value
// and a boolean to check if the value has been set.
func (o *RegisterTokenModel) GetUpdatedOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Updated, true
}

// SetUpdated sets field value
func (o *RegisterTokenModel) SetUpdated(v int64) {
	o.Updated = v
}

// GetVersion returns the Version field value
func (o *RegisterTokenModel) GetVersion() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *RegisterTokenModel) GetVersionOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *RegisterTokenModel) SetVersion(v int64) {
	o.Version = v
}

func (o RegisterTokenModel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegisterTokenModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["created"] = o.Created
	toSerialize["created_by"] = o.CreatedBy
	toSerialize["id"] = o.Id
	toSerialize["parent_id"] = o.ParentId
	toSerialize["scope"] = o.Scope
	toSerialize["token"] = o.Token
	toSerialize["updated"] = o.Updated
	toSerialize["version"] = o.Version
	return toSerialize, nil
}

func (o *RegisterTokenModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"created",
		"created_by",
		"id",
		"parent_id",
		"scope",
		"token",
		"updated",
		"version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegisterTokenModel := _RegisterTokenModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRegisterTokenModel)

	if err != nil {
		return err
	}

	*o = RegisterTokenModel(varRegisterTokenModel)

	return err
}

type NullableRegisterTokenModel struct {
	value *RegisterTokenModel
	isSet bool
}

func (v NullableRegisterTokenModel) Get() *RegisterTokenModel {
	return v.value
}

func (v *NullableRegisterTokenModel) Set(val *RegisterTokenModel) {
	v.value = val
	v.isSet = true
}

func (v NullableRegisterTokenModel) IsSet() bool {
	return v.isSet
}

func (v *NullableRegisterTokenModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegisterTokenModel(val *RegisterTokenModel) *NullableRegisterTokenModel {
	return &NullableRegisterTokenModel{value: val, isSet: true}
}

func (v NullableRegisterTokenModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegisterTokenModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
