/*
GitBundle API

GitBundle API documentation.

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbundlesdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RepoSymlinkContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RepoSymlinkContent{}

// RepoSymlinkContent struct for RepoSymlinkContent
type RepoSymlinkContent struct {
	Size int32 `json:"size"`
	Target string `json:"target"`
}

type _RepoSymlinkContent RepoSymlinkContent

// NewRepoSymlinkContent instantiates a new RepoSymlinkContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRepoSymlinkContent(size int32, target string) *RepoSymlinkContent {
	this := RepoSymlinkContent{}
	this.Size = size
	this.Target = target
	return &this
}

// NewRepoSymlinkContentWithDefaults instantiates a new RepoSymlinkContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRepoSymlinkContentWithDefaults() *RepoSymlinkContent {
	this := RepoSymlinkContent{}
	return &this
}

// GetSize returns the Size field value
func (o *RepoSymlinkContent) GetSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *RepoSymlinkContent) GetSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *RepoSymlinkContent) SetSize(v int32) {
	o.Size = v
}

// GetTarget returns the Target field value
func (o *RepoSymlinkContent) GetTarget() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Target
}

// GetTargetOk returns a tuple with the Target field value
// and a boolean to check if the value has been set.
func (o *RepoSymlinkContent) GetTargetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Target, true
}

// SetTarget sets field value
func (o *RepoSymlinkContent) SetTarget(v string) {
	o.Target = v
}

func (o RepoSymlinkContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RepoSymlinkContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["size"] = o.Size
	toSerialize["target"] = o.Target
	return toSerialize, nil
}

func (o *RepoSymlinkContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"size",
		"target",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRepoSymlinkContent := _RepoSymlinkContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRepoSymlinkContent)

	if err != nil {
		return err
	}

	*o = RepoSymlinkContent(varRepoSymlinkContent)

	return err
}

type NullableRepoSymlinkContent struct {
	value *RepoSymlinkContent
	isSet bool
}

func (v NullableRepoSymlinkContent) Get() *RepoSymlinkContent {
	return v.value
}

func (v *NullableRepoSymlinkContent) Set(val *RepoSymlinkContent) {
	v.value = val
	v.isSet = true
}

func (v NullableRepoSymlinkContent) IsSet() bool {
	return v.isSet
}

func (v *NullableRepoSymlinkContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRepoSymlinkContent(val *RepoSymlinkContent) *NullableRepoSymlinkContent {
	return &NullableRepoSymlinkContent{value: val, isSet: true}
}

func (v NullableRepoSymlinkContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRepoSymlinkContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


