/*
GitBundle API

GitBundle API documentation.

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbundlesdk

import (
	"encoding/json"
)

// checks if the QueryOption type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueryOption{}

// QueryOption struct for QueryOption
type QueryOption struct {
	Page *int64 `json:"page,omitempty"`
	Size *int64 `json:"size,omitempty"`
	Query *string `json:"query,omitempty"`
}

// NewQueryOption instantiates a new QueryOption object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueryOption() *QueryOption {
	this := QueryOption{}
	return &this
}

// NewQueryOptionWithDefaults instantiates a new QueryOption object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryOptionWithDefaults() *QueryOption {
	this := QueryOption{}
	return &this
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *QueryOption) GetPage() int64 {
	if o == nil || IsNil(o.Page) {
		var ret int64
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryOption) GetPageOk() (*int64, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *QueryOption) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given int64 and assigns it to the Page field.
func (o *QueryOption) SetPage(v int64) {
	o.Page = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *QueryOption) GetSize() int64 {
	if o == nil || IsNil(o.Size) {
		var ret int64
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryOption) GetSizeOk() (*int64, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *QueryOption) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int64 and assigns it to the Size field.
func (o *QueryOption) SetSize(v int64) {
	o.Size = &v
}

// GetQuery returns the Query field value if set, zero value otherwise.
func (o *QueryOption) GetQuery() string {
	if o == nil || IsNil(o.Query) {
		var ret string
		return ret
	}
	return *o.Query
}

// GetQueryOk returns a tuple with the Query field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryOption) GetQueryOk() (*string, bool) {
	if o == nil || IsNil(o.Query) {
		return nil, false
	}
	return o.Query, true
}

// HasQuery returns a boolean if a field has been set.
func (o *QueryOption) HasQuery() bool {
	if o != nil && !IsNil(o.Query) {
		return true
	}

	return false
}

// SetQuery gets a reference to the given string and assigns it to the Query field.
func (o *QueryOption) SetQuery(v string) {
	o.Query = &v
}

func (o QueryOption) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueryOption) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.Query) {
		toSerialize["query"] = o.Query
	}
	return toSerialize, nil
}

type NullableQueryOption struct {
	value *QueryOption
	isSet bool
}

func (v NullableQueryOption) Get() *QueryOption {
	return v.value
}

func (v *NullableQueryOption) Set(val *QueryOption) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryOption) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryOption) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryOption(val *QueryOption) *NullableQueryOption {
	return &NullableQueryOption{value: val, isSet: true}
}

func (v NullableQueryOption) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryOption) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


