/*
 * GitBundle API
 *
 * GitBundle API documentation.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Permission : Permission represents the different types of permissions a principal can have.
/// Permission represents the different types of permissions a principal can have.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Permission {
    #[serde(rename = "group_view")]
    GroupView,
    #[serde(rename = "group_edit")]
    GroupEdit,
    #[serde(rename = "group_delete")]
    GroupDelete,
    #[serde(rename = "repo_view")]
    RepoView,
    #[serde(rename = "repo_edit")]
    RepoEdit,
    #[serde(rename = "repo_delete")]
    RepoDelete,
    #[serde(rename = "repo_push")]
    RepoPush,
    #[serde(rename = "repo_report_commit_check")]
    RepoReportCommitCheck,
    #[serde(rename = "user_view")]
    UserView,
    #[serde(rename = "user_edit")]
    UserEdit,
    #[serde(rename = "user_delete")]
    UserDelete,
    #[serde(rename = "user_edit_admin")]
    UserEditAdmin,
    #[serde(rename = "service_account_view")]
    ServiceAccountView,
    #[serde(rename = "service_account_edit")]
    ServiceAccountEdit,
    #[serde(rename = "service_account_delete")]
    ServiceAccountDelete,
    #[serde(rename = "service_view")]
    ServiceView,
    #[serde(rename = "service_edit")]
    ServiceEdit,
    #[serde(rename = "service_delete")]
    ServiceDelete,
    #[serde(rename = "service_edit_admin")]
    ServiceEditAdmin,
    #[serde(rename = "action_view")]
    ActionView,
    #[serde(rename = "action_edit")]
    ActionEdit,
    #[serde(rename = "action_delete")]
    ActionDelete,
    #[serde(rename = "action_execute")]
    ActionExecute,
    #[serde(rename = "secret_view")]
    SecretView,
    #[serde(rename = "secret_edit")]
    SecretEdit,
    #[serde(rename = "secret_delete")]
    SecretDelete,
    #[serde(rename = "secret_access")]
    SecretAccess,
    #[serde(rename = "connector_view")]
    ConnectorView,
    #[serde(rename = "connector_edit")]
    ConnectorEdit,
    #[serde(rename = "connector_delete")]
    ConnectorDelete,
    #[serde(rename = "connector_access")]
    ConnectorAccess,
    #[serde(rename = "template_view")]
    TemplateView,
    #[serde(rename = "template_edit")]
    TemplateEdit,
    #[serde(rename = "template_delete")]
    TemplateDelete,
    #[serde(rename = "template_access")]
    TemplateAccess,

}

impl std::fmt::Display for Permission {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::GroupView => write!(f, "group_view"),
            Self::GroupEdit => write!(f, "group_edit"),
            Self::GroupDelete => write!(f, "group_delete"),
            Self::RepoView => write!(f, "repo_view"),
            Self::RepoEdit => write!(f, "repo_edit"),
            Self::RepoDelete => write!(f, "repo_delete"),
            Self::RepoPush => write!(f, "repo_push"),
            Self::RepoReportCommitCheck => write!(f, "repo_report_commit_check"),
            Self::UserView => write!(f, "user_view"),
            Self::UserEdit => write!(f, "user_edit"),
            Self::UserDelete => write!(f, "user_delete"),
            Self::UserEditAdmin => write!(f, "user_edit_admin"),
            Self::ServiceAccountView => write!(f, "service_account_view"),
            Self::ServiceAccountEdit => write!(f, "service_account_edit"),
            Self::ServiceAccountDelete => write!(f, "service_account_delete"),
            Self::ServiceView => write!(f, "service_view"),
            Self::ServiceEdit => write!(f, "service_edit"),
            Self::ServiceDelete => write!(f, "service_delete"),
            Self::ServiceEditAdmin => write!(f, "service_edit_admin"),
            Self::ActionView => write!(f, "action_view"),
            Self::ActionEdit => write!(f, "action_edit"),
            Self::ActionDelete => write!(f, "action_delete"),
            Self::ActionExecute => write!(f, "action_execute"),
            Self::SecretView => write!(f, "secret_view"),
            Self::SecretEdit => write!(f, "secret_edit"),
            Self::SecretDelete => write!(f, "secret_delete"),
            Self::SecretAccess => write!(f, "secret_access"),
            Self::ConnectorView => write!(f, "connector_view"),
            Self::ConnectorEdit => write!(f, "connector_edit"),
            Self::ConnectorDelete => write!(f, "connector_delete"),
            Self::ConnectorAccess => write!(f, "connector_access"),
            Self::TemplateView => write!(f, "template_view"),
            Self::TemplateEdit => write!(f, "template_edit"),
            Self::TemplateDelete => write!(f, "template_delete"),
            Self::TemplateAccess => write!(f, "template_access"),
        }
    }
}

impl Default for Permission {
    fn default() -> Permission {
        Self::GroupView
    }
}

