/*
 * GitBundle API
 *
 * GitBundle API documentation.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TriggerEvent {
    #[serde(rename = "cron")]
    Cron,
    #[serde(rename = "manual")]
    Manual,
    #[serde(rename = "push")]
    Push,
    #[serde(rename = "pull_request")]
    PullRequest,
    #[serde(rename = "tag")]
    Tag,

}

impl std::fmt::Display for TriggerEvent {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Cron => write!(f, "cron"),
            Self::Manual => write!(f, "manual"),
            Self::Push => write!(f, "push"),
            Self::PullRequest => write!(f, "pull_request"),
            Self::Tag => write!(f, "tag"),
        }
    }
}

impl Default for TriggerEvent {
    fn default() -> TriggerEvent {
        Self::Cron
    }
}

